// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";
import * as TinyColor$RescriptTinycolor from "rescript-tinycolor/src/TinyColor.bs.js";

function GradientRadialBackground(Props) {
  var s = Props.style;
  var stops = Props.stops;
  var children = Props.children;
  var stopsAsString = Belt_Array.joinWith(Belt_Array.map(stops, (function (stop) {
              return Belt_Option.getWithDefault(Belt_Option.map(TinyColor$RescriptTinycolor.makeFromString(stop.stopColor), (function (c) {
                                return TinyColor$RescriptTinycolor.setAlpha(Number(stop.stopOpacity), c).toString();
                              })), "#000") + " " + stop.offset;
            })), ", ", (function (s) {
          return s;
        }));
  var gradientStyleAsString = "radial-gradient(circle at 0 0, " + stopsAsString + ")";
  return ReactNative.unstable_createElement("div", {
              style: [
                s,
                {
                  display: "flex",
                  flexDirection: "column"
                },
                {
                  backgroundImage: gradientStyleAsString
                }
              ]
            }, children);
}

var make = GradientRadialBackground;

export {
  make ,
  
}
/* react-native Not a pure module */
