// Generated by ReScript, PLEASE EDIT WITH CARE

import * as T from "../T.bs.js";
import * as Font from "../components/shareable/Font.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as PostList from "../components/PostList.bs.js";
import Head from "next/head";
import * as AppWrapper from "../components/AppWrapper.bs.js";
import * as BackendApi from "../BackendApi.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as BlogFrontend from "../BlogFrontend.bs.js";
import * as ReactNative from "react-native";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as Container$ReactMultiversal from "react-multiversal/src/Container.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var Malformed = {};

function PageBlog(Props) {
  var posts = Props.posts;
  var malformed = Props.malformed;
  var theme = Curry._2(T.useTheme, undefined, undefined);
  Belt_Array.map(malformed, (function (prim) {
          console.error(prim);
          
        }));
  return React.createElement(AppWrapper.make, {
              children: null
            }, React.createElement(Head, {
                  children: React.createElement("title", undefined, "Blog - " + Consts.defaultTitle)
                }), React.createElement(ReactNative.View, {
                  style: theme.styles.back,
                  children: React.createElement(Container$ReactMultiversal.make, {
                        children: null
                      }, React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                            children: "Latest",
                            style: [
                              Font.ios.subtitle1,
                              theme.styles.textLight1
                            ]
                          }), React.createElement(ReactNative.Text, {
                            children: "Posts",
                            style: [
                              Font.iosEm.largeTitle,
                              theme.styles.text
                            ]
                          }), React.createElement(SpacedView$ReactMultiversal.make, {
                            children: React.createElement(PostList.make, {
                                  posts: posts
                                })
                          }), React.createElement(Spacer$ReactMultiversal.make, {
                            size: /* L */2
                          }))
                }));
}

function $$default(props) {
  return PageBlog({
              posts: props.posts,
              malformed: props.malformed
            });
}

function getStaticProps(_ctx) {
  var match = Belt_Array.reduce(BackendApi.getAll("blog"), [
        [],
        []
      ], (function (acc, postData) {
          var malformed = acc[1];
          var posts = acc[0];
          var __x = postData.json;
          var decoded = BlogFrontend.decode(postData.slug, __x);
          if (decoded.TAG !== /* Ok */0) {
            return [
                    posts,
                    Belt_Array.concat(malformed, [{
                            id: postData.slug,
                            message: decoded._0
                          }])
                  ];
          }
          posts.push(decoded._0);
          return [
                  posts,
                  malformed
                ];
        }));
  return Promise.resolve({
              props: {
                posts: BlogFrontend.orderByDate(match[0]),
                malformed: match[1]
              }
            });
}

var make = PageBlog;

export {
  Malformed ,
  make ,
  $$default ,
  $$default as default,
  getStaticProps ,
  
}
/* T Not a pure module */
