// Generated by ReScript, PLEASE EDIT WITH CARE

import * as T from "../T.bs.js";
import * as Font from "../components/shareable/Font.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as Skills from "../components/Skills.bs.js";
import * as PostList from "../components/PostList.bs.js";
import * as TextLink from "../components/TextLink.bs.js";
import Head from "next/head";
import * as AppWrapper from "../components/AppWrapper.bs.js";
import * as BackendApi from "../BackendApi.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as LinkButton from "../components/LinkButton.bs.js";
import * as BlogFrontend from "../BlogFrontend.bs.js";
import * as ReactNative from "react-native";
import * as JumbotronApps from "../components/JumbotronApps.bs.js";
import * as SVGCompanyAirbus from "../../assets/SVGs/components/SVGCompanyAirbus.bs.js";
import * as SVGCompanyGoogle from "../../assets/SVGs/components/SVGCompanyGoogle.bs.js";
import * as SVGCompanyTwitter from "../../assets/SVGs/components/SVGCompanyTwitter.bs.js";
import * as SVGCompanyFacebook from "../../assets/SVGs/components/SVGCompanyFacebook.bs.js";
import * as UnderlinedTextLink from "../components/UnderlinedTextLink.bs.js";
import * as BlocksAboutMySkills from "../components/BlocksAboutMySkills.bs.js";
import * as SVGCompanyAlltricks from "../../assets/SVGs/components/SVGCompanyAlltricks.bs.js";
import * as SVGCompanyMicrosoft from "../../assets/SVGs/components/SVGCompanyMicrosoft.bs.js";
import * as SVGCompanyMolotovTv from "../../assets/SVGs/components/SVGCompanyMolotovTv.bs.js";
import * as Row$ReactMultiversal from "react-multiversal/src/Row.bs.js";
import * as SVGCompanyKisioDigital from "../../assets/SVGs/components/SVGCompanyKisioDigital.bs.js";
import * as Center$ReactMultiversal from "react-multiversal/src/Center.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as TitlePre$ReactMultiversal from "react-multiversal/src/TitlePre.bs.js";
import * as Container$ReactMultiversal from "react-multiversal/src/Container.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";
import * as LinkContactBubbleFixedBottom from "../components/LinkContactBubbleFixedBottom.bs.js";

var Malformed = {};

var styles = ReactNative.StyleSheet.create({
      button: {
        width: 200
      },
      logoStyle: {
        filter: "grayscale(100%) contrast(25%) brightness(150%)"
      }
    });

function PageDev(Props) {
  var posts = Props.posts;
  var malformed = Props.malformed;
  var theme = Curry._2(T.useTheme, undefined, undefined);
  Belt_Array.map(malformed, (function (prim) {
          console.error(prim);
          
        }));
  return React.createElement(AppWrapper.make, {
              children: null
            }, React.createElement(Head, {
                  children: React.createElement("title", undefined, Consts.title + (", React & React Native " + Consts.defaultTitle))
                }), React.createElement(LinkContactBubbleFixedBottom.make, {}), React.createElement(ReactNative.View, {
                  style: theme.styles.back,
                  children: null
                }, React.createElement(JumbotronApps.make, {
                      scrollYAnimatedValue: AppWrapper.scrollYAnimatedValue
                    }), React.createElement(BlocksAboutMySkills.make, {}), React.createElement(Container$ReactMultiversal.make, {
                      wrapperStyle: theme.styles.backDark,
                      children: null
                    }, React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* L */2
                        }), React.createElement(Container$ReactMultiversal.make, {
                          maxWidth: 1600,
                          children: null
                        }, React.createElement(Spacer$ReactMultiversal.make, {
                              size: /* L */2
                            }), React.createElement(Center$ReactMultiversal.make, {
                              children: React.createElement(TitlePre$ReactMultiversal.make, {
                                    children: "COMPANIES THAT TRIED TO HIRE ME"
                                  })
                            }), React.createElement(Row$ReactMultiversal.Wrap.Center.make, {
                              children: null
                            }, React.createElement(SVGCompanyFacebook.make, {
                                  width: 200,
                                  height: 200,
                                  style: styles.logoStyle
                                }), React.createElement(SVGCompanyTwitter.make, {
                                  width: 200,
                                  height: 200,
                                  style: styles.logoStyle
                                }), React.createElement(SVGCompanyMicrosoft.make, {
                                  width: 200,
                                  height: 200,
                                  style: styles.logoStyle
                                }), React.createElement(SVGCompanyGoogle.make, {
                                  width: 200,
                                  height: 200,
                                  style: styles.logoStyle
                                }))), React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* L */2
                        }), React.createElement(Center$ReactMultiversal.make, {
                          children: React.createElement(TitlePre$ReactMultiversal.make, {
                                children: "THINGS I LIKE TO WORK WITH"
                              })
                        }), React.createElement(Skills.make, {}), React.createElement(Center$ReactMultiversal.make, {
                          children: React.createElement(UnderlinedTextLink.make, {
                                href: "/resume/",
                                style: {
                                  color: "#bbc",
                                  fontSize: 14,
                                  fontWeight: "200"
                                },
                                children: "And more"
                              })
                        }), React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* L */2
                        })), React.createElement(Container$ReactMultiversal.make, {
                      maxWidth: 1600,
                      children: null
                    }, React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* L */2
                        }), React.createElement(Center$ReactMultiversal.make, {
                          children: React.createElement(TitlePre$ReactMultiversal.make, {
                                children: "🇫🇷 FRENCH COMPANIES THAT TRUSTED ME"
                              })
                        }), React.createElement(Row$ReactMultiversal.Wrap.Center.make, {
                          children: null
                        }, React.createElement(SVGCompanyMolotovTv.make, {
                              width: 200,
                              height: 200,
                              style: styles.logoStyle
                            }), React.createElement(SVGCompanyAlltricks.make, {
                              width: 200,
                              height: 200,
                              style: styles.logoStyle
                            }), React.createElement(SVGCompanyKisioDigital.make, {
                              width: 200,
                              height: 200,
                              style: styles.logoStyle
                            }), React.createElement(SVGCompanyAirbus.make, {
                              width: 200,
                              height: 200,
                              style: styles.logoStyle
                            }))), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(SpacedView$ReactMultiversal.make, {
                      vertical: /* L */2,
                      style: {
                        backgroundColor: Consts.Colors.dark
                      },
                      children: React.createElement(Center$ReactMultiversal.make, {
                            children: null
                          }, React.createElement(TitlePre$ReactMultiversal.make, {
                                children: "Interested with my profile ?"
                              }), React.createElement(Spacer$ReactMultiversal.make, {
                                size: /* L */2
                              }), React.createElement(Row$ReactMultiversal.Wrap.Center.make, {
                                children: null
                              }, React.createElement(SpacedView$ReactMultiversal.make, {
                                    horizontal: /* XS */5,
                                    children: React.createElement(LinkButton.make, {
                                          href: "/resume/",
                                          textSize: 24,
                                          mode: /* Outlined */2,
                                          style: styles.button,
                                          color: Consts.Colors.lightest,
                                          color2: Consts.Colors.dark,
                                          children: null
                                        }, React.createElement(ReactNative.Text, {
                                              children: "Learn more"
                                            }), React.createElement(ReactNative.Text, {
                                              children: "\nCheck out my resume",
                                              style: {
                                                fontSize: 12,
                                                fontWeight: "300"
                                              }
                                            }))
                                  }), React.createElement(SpacedView$ReactMultiversal.make, {
                                    horizontal: /* XS */5,
                                    children: React.createElement(LinkButton.make, {
                                          href: "/contact/",
                                          textSize: 24,
                                          style: styles.button,
                                          color: Consts.Colors.lightest,
                                          color2: Consts.Colors.dark,
                                          children: null
                                        }, React.createElement(ReactNative.Text, {
                                              children: "Hire me"
                                            }), React.createElement(ReactNative.Text, {
                                              children: "\nCheck out availabilities",
                                              style: {
                                                fontSize: 12,
                                                fontWeight: "300"
                                              }
                                            }))
                                  })))
                    }), React.createElement(Container$ReactMultiversal.make, {
                      children: React.createElement(SpacedView$ReactMultiversal.make, {
                            vertical: /* L */2,
                            children: null
                          }, React.createElement(Center$ReactMultiversal.make, {
                                children: React.createElement(ReactNative.Text, {
                                      children: "Latest Posts on the Blog",
                                      style: [
                                        Font.iosEm.title1,
                                        theme.styles.text
                                      ]
                                    })
                              }), React.createElement(ReactNative.View, {
                                children: null
                              }, React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(PostList.make, {
                                    posts: posts
                                  }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(Row$ReactMultiversal.Center.make, {
                                    children: React.createElement(TextLink.make, {
                                          children: "More posts",
                                          href: "/blog/",
                                          style: [
                                            Font.iosEm.caption,
                                            theme.styles.text
                                          ]
                                        })
                                  })))
                    })));
}

function $$default(props) {
  return PageDev({
              posts: props.posts,
              malformed: props.malformed
            });
}

function getStaticProps(_ctx) {
  var match = Belt_Array.reduce(BackendApi.getAll("blog"), [
        [],
        []
      ], (function (acc, postData) {
          var malformed = acc[1];
          var posts = acc[0];
          var __x = postData.json;
          var decoded = BlogFrontend.decode(postData.slug, __x);
          if (decoded.TAG !== /* Ok */0) {
            return [
                    posts,
                    Belt_Array.concat(malformed, [{
                            id: postData.slug,
                            message: decoded._0
                          }])
                  ];
          }
          posts.push(decoded._0);
          return [
                  posts,
                  malformed
                ];
        }));
  return Promise.resolve({
              props: {
                posts: Belt_Array.slice(BlogFrontend.orderByDate(match[0]), 0, 5),
                malformed: match[1]
              }
            });
}

var make = PageDev;

export {
  Malformed ,
  styles ,
  make ,
  $$default ,
  $$default as default,
  getStaticProps ,
  
}
/* styles Not a pure module */
