// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as TextLink from "../components/TextLink.bs.js";
import Head from "next/head";
import * as AppWrapper from "../components/AppWrapper.bs.js";
import * as ReactNative from "react-native";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as Container$ReactMultiversal from "react-multiversal/src/Container.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";
import * as ImageFromUri$ReactMultiversal from "react-multiversal/src/ImageFromUri.bs.js";
import * as ScreenHeader$ReactMultiversal from "react-multiversal/src/ScreenHeader.bs.js";

function PageApps(Props) {
  return React.createElement(AppWrapper.make, {
              children: null
            }, React.createElement(Head, {
                  children: React.createElement("title", undefined, Consts.title + (", React & React Native " + Consts.defaultTitle))
                }), React.createElement(ReactNative.View, {
                  style: Predefined$ReactMultiversal.styles.flex,
                  children: React.createElement(Container$ReactMultiversal.make, {
                        wrapperStyle: {
                          backgroundColor: Consts.Colors.light
                        },
                        children: null
                      }, React.createElement(ScreenHeader$ReactMultiversal.make, {
                            title: "Apps"
                          }), React.createElement(Spacer$ReactMultiversal.make, {
                            size: /* L */2
                          }), React.createElement(ReactNative.View, {
                            style: Predefined$ReactMultiversal.styles.rowWrap,
                            children: null
                          }, React.createElement(SpacedView$ReactMultiversal.make, {
                                vertical: /* S */4,
                                horizontal: /* S */4,
                                children: React.createElement(ImageFromUri$ReactMultiversal.make, {
                                      uri: "/apps/lifetime/icon.png",
                                      style: {
                                        borderRadius: 96 * 0.175,
                                        height: 96,
                                        width: 96
                                      }
                                    })
                              }), React.createElement(SpacedView$ReactMultiversal.make, {
                                vertical: /* S */4,
                                horizontal: /* S */4,
                                style: {
                                  flexBasis: 180,
                                  flexGrow: 1,
                                  flexShrink: 1
                                },
                                children: null
                              }, React.createElement(TextLink.make, {
                                    children: "LifeTime",
                                    href: "/apps/lifetime",
                                    style: {
                                      fontSize: 36,
                                      fontWeight: "bold",
                                      lineHeight: 36
                                    }
                                  }), React.createElement(Spacer$ReactMultiversal.make, {
                                    size: /* S */4
                                  }), React.createElement(ReactNative.View, {
                                    style: Predefined$ReactMultiversal.styles.flexShrink,
                                    children: React.createElement(ReactNative.Text, {
                                          children: "A personal coach that shows you clearly your daily activities, and help you to reach your goals.",
                                          style: {
                                            fontSize: 16,
                                            flexShrink: 1
                                          }
                                        })
                                  }), React.createElement(Spacer$ReactMultiversal.make, {
                                    size: /* S */4
                                  }), React.createElement(ReactNative.View, {
                                    style: [
                                      Predefined$ReactMultiversal.styles.rowWrap,
                                      Predefined$ReactMultiversal.styles.flexShrink,
                                      {
                                        justifyContent: "flex-end"
                                      }
                                    ],
                                    children: null
                                  }, React.createElement("a", {
                                        href: "https://testflight.apple.com/join/HZJj4kel"
                                      }, React.createElement(SpacedView$ReactMultiversal.make, {
                                            vertical: /* S */4,
                                            horizontal: /* S */4,
                                            children: React.createElement("img", {
                                                  height: "48",
                                                  src: "https://developer.apple.com/app-store/marketing/guidelines/images/badge-example-preferred_2x.png"
                                                })
                                          })), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement("a", {
                                        href: "https://play.google.com/store/apps/details?id=io.moox.lifetime"
                                      }, React.createElement(Spacer$ReactMultiversal.make, {
                                            size: /* XXS */6
                                          }), React.createElement("img", {
                                            height: "70",
                                            src: "https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png"
                                          }))))), React.createElement(Spacer$ReactMultiversal.make, {
                            size: /* L */2
                          }), React.createElement(ReactNative.View, {
                            style: Predefined$ReactMultiversal.styles.rowWrap,
                            children: null
                          }, React.createElement(SpacedView$ReactMultiversal.make, {
                                vertical: /* S */4,
                                horizontal: /* S */4,
                                children: React.createElement(ImageFromUri$ReactMultiversal.make, {
                                      uri: "/apps/hide-the-notch/icon.png",
                                      style: {
                                        borderRadius: 96 * 0.175,
                                        height: 96,
                                        width: 96
                                      }
                                    })
                              }), React.createElement(SpacedView$ReactMultiversal.make, {
                                vertical: /* S */4,
                                horizontal: /* S */4,
                                style: {
                                  flexBasis: 180,
                                  flexGrow: 1,
                                  flexShrink: 1
                                },
                                children: null
                              }, React.createElement(TextLink.make, {
                                    children: "Hide The Notch",
                                    href: "/apps/hide-the-notch",
                                    style: {
                                      fontSize: 36,
                                      fontWeight: "bold",
                                      lineHeight: 36
                                    }
                                  }), React.createElement(Spacer$ReactMultiversal.make, {
                                    size: /* S */4
                                  }), React.createElement(ReactNative.Text, {
                                    children: "Simple app to hide your notch.",
                                    style: {
                                      fontSize: 16
                                    }
                                  }), React.createElement(Spacer$ReactMultiversal.make, {
                                    size: /* S */4
                                  }), React.createElement(ReactNative.View, {
                                    style: [
                                      Predefined$ReactMultiversal.styles.rowWrap,
                                      {
                                        justifyContent: "flex-end"
                                      }
                                    ],
                                    children: React.createElement("a", {
                                          href: "https://apps.apple.com/us/app/hide-the-notch/id1312839983?ls=1"
                                        }, React.createElement(SpacedView$ReactMultiversal.make, {
                                              vertical: /* S */4,
                                              horizontal: /* S */4,
                                              children: React.createElement("img", {
                                                    height: "48",
                                                    src: "https://developer.apple.com/app-store/marketing/guidelines/images/badge-example-preferred_2x.png"
                                                  })
                                            }))
                                  }))))
                }));
}

var make = PageApps;

var $$default = PageApps;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
