// Generated by ReScript, PLEASE EDIT WITH CARE

import * as T from "../T.bs.js";
import * as Font from "../components/shareable/Font.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as SVGFlow from "../../assets/SVGs/components/SVGFlow.bs.js";
import * as SVGJest from "../../assets/SVGs/components/SVGJest.bs.js";
import * as SVGReact from "../../assets/SVGs/components/SVGReact.bs.js";
import * as ViewLink from "../components/ViewLink.bs.js";
import * as SVGApollo from "../../assets/SVGs/components/SVGApollo.bs.js";
import * as SVGSketch from "../../assets/SVGs/components/SVGSketch.bs.js";
import Head from "next/head";
import * as AppWrapper from "../components/AppWrapper.bs.js";
import * as BackendApi from "../BackendApi.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as SVGGraphql from "../../assets/SVGs/components/SVGGraphql.bs.js";
import * as SVGWebpack from "../../assets/SVGs/components/SVGWebpack.bs.js";
import * as SVGTraining from "../../assets/SVGs/components/SVGTraining.bs.js";
import * as SVGPhotoshop from "../../assets/SVGs/components/SVGPhotoshop.bs.js";
import * as ReactNative from "react-native";
import * as SVGJavaScript from "../../assets/SVGs/components/SVGJavaScript.bs.js";
import * as SVGMicrophone from "../../assets/SVGs/components/SVGMicrophone.bs.js";
import * as ResumeFrontend from "../ResumeFrontend.bs.js";
import * as ResumeTimeline from "../components/ResumeTimeline.bs.js";
import * as SVGActivityDiy from "../../assets/SVGs/components/SVGActivityDiy.bs.js";
import * as SVGCommandLine from "../../assets/SVGs/components/SVGCommandLine.bs.js";
import * as SVGDevRescript from "../../assets/SVGs/components/SVGDevRescript.bs.js";
import * as SVGActivityBike from "../../assets/SVGs/components/SVGActivityBike.bs.js";
import * as SVGDevTypescript from "../../assets/SVGs/components/SVGDevTypescript.bs.js";
import * as WindowSizeFilter from "../components/WindowSizeFilter.bs.js";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as SVGActivityRunning from "../../assets/SVGs/components/SVGActivityRunning.bs.js";
import * as SVGActivityStandup from "../../assets/SVGs/components/SVGActivityStandup.bs.js";
import * as SVGActivityCrossfit from "../../assets/SVGs/components/SVGActivityCrossfit.bs.js";
import * as SVGActivityWakeboard from "../../assets/SVGs/components/SVGActivityWakeboard.bs.js";
import * as Center$ReactMultiversal from "react-multiversal/src/Center.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as GradientLinearBackground from "../components/shareable/GradientLinearBackground.bs.js";
import * as Container$ReactMultiversal from "react-multiversal/src/Container.bs.js";
import * as JumbotronCreativeDeveloper from "../components/JumbotronCreativeDeveloper.bs.js";
import * as SVGArrowRoundedWithTailTop from "../../assets/SVGs/components/SVGArrowRoundedWithTailTop.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";
import * as FixedBottom$ReactMultiversal from "react-multiversal/src/FixedBottom.bs.js";
import * as SVGActivityObstacleCourseRace from "../../assets/SVGs/components/SVGActivityObstacleCourseRace.bs.js";
import * as TabBarWrapper$ReactMultiversal from "react-multiversal/src/TabBarWrapper.bs.js";

var Malformed = {};

var currentYear = new Date().getFullYear() | 0;

var styles = ReactNative.StyleSheet.create({
      textStrong: {
        color: Consts.Colors.dark,
        fontSize: 32,
        fontWeight: "800"
      },
      textLight: {
        color: Consts.Colors.dark,
        fontSize: 28,
        fontWeight: "200"
      },
      nanoTitle: {
        color: "#bbc",
        fontSize: 14,
        fontWeight: "600",
        textAlign: "center"
      },
      iconText: {
        color: "#bbc",
        fontSize: 12,
        fontWeight: "300",
        lineHeight: 14,
        textAlign: "center",
        left: 0,
        position: "absolute",
        right: 0,
        top: 64
      },
      activities: {
        alignItems: "flex-start",
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center"
      }
    });

var grayIconDomStyle = {
  display: "flex",
  flex: "1 1 auto",
  flexDirection: "column",
  filter: [
      "grayscale(1)",
      "brightness(0.9)",
      "contrast(0.6)",
      "opacity(0.6)"
    ].join(" ")
};

function PageResume(Props) {
  var items = Props.items;
  var malformed = Props.malformed;
  var theme = Curry._2(T.useTheme, undefined, undefined);
  Belt_Array.map(malformed, (function (prim) {
          console.error(prim);
          
        }));
  return React.createElement(AppWrapper.make, {
              children: null
            }, React.createElement(Head, {
                  children: React.createElement("title", undefined, "Resume - " + Consts.defaultTitle)
                }), React.createElement(ReactNative.View, {
                  style: [{
                      zIndex: 1
                    }],
                  children: React.createElement(JumbotronCreativeDeveloper.make, {})
                }), React.createElement(Container$ReactMultiversal.make, {
                  style: [
                    theme.styles.back,
                    {
                      zIndex: 0
                    }
                  ],
                  children: null
                }, React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* XXL */0
                    }), React.createElement(SpacedView$ReactMultiversal.make, {
                      style: Predefined$ReactMultiversal.styles.rowWrapCenter,
                      children: null
                    }, React.createElement(SpacedView$ReactMultiversal.make, {
                          horizontal: /* S */4,
                          style: {
                            alignItems: "center",
                            flex: 1,
                            justifyContent: "center",
                            maxWidth: 310,
                            minWidth: 240
                          },
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "THINGS I WORK WITH",
                              style: styles.nanoTitle
                            }), React.createElement(ReactNative.View, {
                              style: styles.activities,
                              children: null
                            }, React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGJavaScript.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "JavaScript",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGReact.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "React",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGDevRescript.make, {
                                          width: 48,
                                          height: 48
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "ReScript",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGJest.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Jest",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGDevTypescript.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "TypeScript",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGFlow.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Flow",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGGraphql.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Graphql",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGApollo.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Apollo",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGWebpack.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Webpack",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGPhotoshop.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Photoshop",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGSketch.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Sketch",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGCommandLine.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "CLI",
                                      style: styles.iconText
                                    })))), React.createElement(SpacedView$ReactMultiversal.make, {
                          horizontal: /* S */4,
                          style: {
                            alignItems: "flex-start",
                            flex: 1,
                            flexBasis: 240,
                            justifyContent: "flex-start"
                          },
                          children: React.createElement(ReactNative.Text, {
                                children: "Hi, I am Maxime Thirouin, also known as MoOx. I live near Toulouse, France.\nI am a software developer specialized in front-end development of mobile & web applications.\nI love to design and develop UIs. I care about UX, responsiveness, performance, maintainability and scalability.\nWhen I am not coding or meditating, I enjoy simple things like gardening, watching a movie or enjoying one of the various activities that life has to offer.",
                                style: [
                                  Font.ios.body,
                                  theme.styles.text
                                ]
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          horizontal: /* S */4,
                          style: {
                            alignItems: "center",
                            flex: 1,
                            justifyContent: "center",
                            maxWidth: 310,
                            minWidth: 240
                          },
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "WEEKLY ACTIVITIES",
                              style: styles.nanoTitle
                            }), React.createElement(ReactNative.View, {
                              style: styles.activities,
                              children: null
                            }, React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityCrossfit.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Crossfit",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityBike.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Bike",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityStandup.make, {
                                          width: 44,
                                          height: 44,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Stand-up",
                                      style: styles.iconText
                                    }))), React.createElement(Spacer$ReactMultiversal.make, {
                              size: /* XS */5
                            }), React.createElement(ReactNative.Text, {
                              children: "REGULAR ACTIVITIES",
                              style: styles.nanoTitle
                            }), React.createElement(ReactNative.View, {
                              style: styles.activities,
                              children: null
                            }, React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityDiy.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Bricolage",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGMicrophone.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Podcast",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityRunning.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Running",
                                      style: styles.iconText
                                    }))), React.createElement(Spacer$ReactMultiversal.make, {
                              size: /* XS */5
                            }), React.createElement(ReactNative.Text, {
                              children: "CASUAL ACTIVITIES",
                              style: styles.nanoTitle
                            }), React.createElement(ReactNative.View, {
                              style: styles.activities,
                              children: null
                            }, React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityObstacleCourseRace.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Obstacle\nRace",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGActivityWakeboard.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Wakeboard",
                                      style: styles.iconText
                                    })), React.createElement(SpacedView$ReactMultiversal.make, {
                                  vertical: /* S */4,
                                  horizontal: /* XS */5,
                                  children: null
                                }, React.createElement("div", {
                                      style: grayIconDomStyle
                                    }, React.createElement(SVGTraining.make, {
                                          width: 48,
                                          height: 48,
                                          fill: "#bbb"
                                        })), React.createElement(Spacer$ReactMultiversal.make, {
                                      size: /* XXS */6
                                    }), React.createElement(ReactNative.Text, {
                                      children: "Teaching",
                                      style: styles.iconText
                                    }))))), React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* XXL */0
                    })), React.createElement(ReactNative.View, {
                  children: null
                }, React.createElement(GradientLinearBackground.make, {
                      style: [
                        ReactNative.StyleSheet.absoluteFill,
                        {
                          transform: [
                            {
                              rotate: Style$ReactNative.deg(3)
                            },
                            {
                              scale: 1.2
                            }
                          ]
                        }
                      ],
                      stops: [
                        {
                          offset: Style$ReactNative.pct(0),
                          stopColor: "#00E2C2",
                          stopOpacity: "1"
                        },
                        {
                          offset: Style$ReactNative.pct(100),
                          stopColor: "#027596",
                          stopOpacity: "1"
                        }
                      ],
                      angle: 90
                    }), React.createElement(ReactNative.View, {
                      style: {
                        alignItems: "flex-start",
                        flexDirection: "row",
                        flexWrap: "wrap",
                        justifyContent: "center"
                      },
                      children: null
                    }, React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* S */4,
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "Klei",
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 64,
                                fontWeight: "700",
                                lineHeight: 66
                              }
                            }), React.createElement(ReactNative.Text, {
                              children: "Klei Aliaj",
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 26,
                                fontWeight: "200",
                                lineHeight: 26
                              }
                            })), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* L */2,
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "French",
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 18,
                                fontWeight: "100",
                                lineHeight: 18
                              }
                            }), React.createElement(ReactNative.Text, {
                              children: null,
                              style: {
                                textAlign: "center"
                              }
                            }, React.createElement(ReactNative.Text, {
                                  children: String(currentYear - 1985 | 0),
                                  style: {
                                    color: Consts.Colors.light,
                                    fontSize: 56,
                                    fontWeight: "100",
                                    lineHeight: 56
                                  }
                                }), React.createElement(ReactNative.Text, {
                                  children: " yo ",
                                  style: {
                                    color: Consts.Colors.light,
                                    fontSize: 18,
                                    fontWeight: "900",
                                    lineHeight: 18
                                  }
                                }))), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* L */2,
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "First website",
                              style: {
                                color: Consts.Colors.light
                              }
                            }), React.createElement(ReactNative.Text, {
                              children: String(currentYear - 1999 | 0),
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 76,
                                fontWeight: "400",
                                lineHeight: 76
                              }
                            }), React.createElement(ReactNative.Text, {
                              children: "years ago",
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 18,
                                fontWeight: "100",
                                lineHeight: 18
                              }
                            })), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* L */2,
                          children: React.createElement(SpacedView$ReactMultiversal.make, {
                                vertical: /* S */4,
                                style: {
                                  backgroundColor: Consts.Colors.light,
                                  alignItems: "center"
                                },
                                children: null
                              }, React.createElement(ReactNative.Text, {
                                    children: "First mobile",
                                    style: {
                                      color: Consts.Colors.dark
                                    }
                                  }), React.createElement(ReactNative.Text, {
                                    children: "web app",
                                    style: {
                                      color: Consts.Colors.dark,
                                      fontSize: 20
                                    }
                                  }), React.createElement(ReactNative.Text, {
                                    children: String(currentYear - 2005 | 0),
                                    style: {
                                      color: Consts.Colors.dark,
                                      fontSize: 76,
                                      fontWeight: "800",
                                      lineHeight: 76
                                    }
                                  }), React.createElement(ReactNative.Text, {
                                    children: " years ago",
                                    style: {
                                      color: Consts.Colors.dark,
                                      fontSize: 18,
                                      fontWeight: "100",
                                      lineHeight: 18
                                    }
                                  }))
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          style: {
                            alignSelf: "flex-end"
                          },
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "Professional for",
                              style: {
                                color: Consts.Colors.light,
                                fontWeight: "200"
                              }
                            }), React.createElement(ReactNative.Text, {
                              children: String(currentYear - 2007 | 0),
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 116,
                                fontWeight: "700",
                                lineHeight: 116,
                                marginTop: -10
                              }
                            }), React.createElement(ReactNative.Text, {
                              children: " years",
                              style: {
                                color: Consts.Colors.light,
                                fontSize: 64,
                                fontWeight: "100",
                                lineHeight: 64,
                                marginTop: -20
                              }
                            })))), React.createElement(Spacer$ReactMultiversal.make, {
                  size: /* XXL */0
                }), React.createElement(Container$ReactMultiversal.make, {
                  children: null
                }, React.createElement(Center$ReactMultiversal.make, {
                      children: React.createElement(ReactNative.Text, {
                            children: "Experiences",
                            style: [
                              Font.iosEm.largeTitle,
                              T.stylesDark.text
                            ]
                          })
                    }), React.createElement(ResumeTimeline.make, {
                      items: items
                    }), React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* XL */1
                    })), React.createElement(FixedBottom$ReactMultiversal.make, {
                  children: null
                }, React.createElement(SpacedView$ReactMultiversal.make, {
                      children: React.createElement(ViewLink.make, {
                            href: "/contact/",
                            children: React.createElement(GradientLinearBackground.make, {
                                  style: {
                                    borderRadius: 60
                                  },
                                  stops: [
                                    {
                                      offset: Style$ReactNative.pct(0),
                                      stopColor: "#00E2C2",
                                      stopOpacity: "1"
                                    },
                                    {
                                      offset: Style$ReactNative.pct(100),
                                      stopColor: "#00d2ff",
                                      stopOpacity: "1"
                                    }
                                  ],
                                  angle: 180,
                                  children: React.createElement(SpacedView$ReactMultiversal.make, {
                                        horizontal: /* L */2,
                                        style: Predefined$ReactMultiversal.styles.rowCenter,
                                        children: null
                                      }, React.createElement(ReactNative.Text, {
                                            children: null,
                                            style: [
                                              Font.iosEm.headline,
                                              T.stylesDark.text
                                            ]
                                          }, "Get in touch", React.createElement(ReactNative.Text, {
                                                children: "\nI am always listening",
                                                style: Font.ios.caption
                                              })), React.createElement(Spacer$ReactMultiversal.make, {
                                            size: /* XS */5
                                          }), React.createElement(ReactNative.View, {
                                            style: {
                                              transform: [{
                                                  rotate: Style$ReactNative.deg(90)
                                                }]
                                            },
                                            children: React.createElement(SVGArrowRoundedWithTailTop.make, {
                                                  width: 36,
                                                  height: 36,
                                                  fill: Consts.Colors.light
                                                })
                                          }))
                                })
                          })
                    }), React.createElement(WindowSizeFilter.SMax.make, {
                      children: React.createElement(TabBarWrapper$ReactMultiversal.Placeholder.make, {})
                    })));
}

function $$default(props) {
  return PageResume({
              items: props.items,
              malformed: props.malformed
            });
}

function getStaticProps(_ctx) {
  var match = Belt_Array.reduce(BackendApi.getAll("resume"), [
        [],
        []
      ], (function (acc, itemData) {
          var malformed = acc[1];
          var items = acc[0];
          var __x = itemData.json;
          var decoded = ResumeFrontend.decode(itemData.slug, __x);
          if (decoded.TAG !== /* Ok */0) {
            return [
                    items,
                    Belt_Array.concat(malformed, [{
                            id: itemData.slug,
                            message: decoded._0
                          }])
                  ];
          }
          items.push(decoded._0);
          return [
                  items,
                  malformed
                ];
        }));
  return Promise.resolve({
              props: {
                items: ResumeFrontend.orderByDate(match[0]),
                malformed: match[1]
              }
            });
}

var make = PageResume;

export {
  Malformed ,
  currentYear ,
  styles ,
  grayIconDomStyle ,
  make ,
  $$default ,
  $$default as default,
  getStaticProps ,
  
}
/* currentYear Not a pure module */
