// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as Skills from "../components/Skills.bs.js";
import * as AppWrapper from "../components/AppWrapper.bs.js";
import * as ReactNative from "react-native";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as Container$ReactMultiversal from "react-multiversal/src/Container.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center"
      },
      text: {
        backgroundColor: Consts.Colors.light,
        alignItems: "center",
        padding: 20,
        width: Style$ReactNative.pct(100)
      },
      textLight: {
        color: Consts.Colors.dark,
        fontSize: 28,
        fontWeight: "200"
      },
      textStrong: {
        color: Consts.Colors.dark,
        fontSize: 32,
        fontWeight: "800"
      },
      row: {
        flexDirection: "row",
        flexWrap: "wrap"
      },
      cell: {
        flex: 1,
        flexBasis: 240
      },
      cellTitle: {
        color: Consts.Colors.dark,
        fontSize: 32,
        fontWeight: "600"
      },
      cellText: {
        color: Consts.Colors.dark,
        fontSize: 16,
        lineHeight: 24
      }
    });

function PageServices(Props) {
  return React.createElement(AppWrapper.make, {
              children: null
            }, React.createElement(Container$ReactMultiversal.make, {
                  maxWidth: 1200,
                  children: null
                }, React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(SpacedView$ReactMultiversal.make, {
                      horizontal: /* None */7,
                      style: styles.container,
                      children: null
                    }, React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* None */7,
                          children: React.createElement(ReactNative.Text, {
                                children: "I make front-ends using React, JavaScript & ReScript. ",
                                style: styles.textLight
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XL */1,
                          style: styles.row,
                          children: null
                        }, React.createElement(SpacedView$ReactMultiversal.make, {
                              vertical: /* None */7,
                              style: styles.cell,
                              children: null
                            }, React.createElement(ReactNative.Text, {
                                  children: "Development",
                                  style: styles.cellTitle
                                }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                                  children: "I am using web technologies since 1995 and made my first mobile app in 2006 and never stopped to learn things since.",
                                  style: styles.cellText
                                })), React.createElement(SpacedView$ReactMultiversal.make, {
                              vertical: /* None */7,
                              style: styles.cell,
                              children: null
                            }, React.createElement(ReactNative.Text, {
                                  children: "Consultancy",
                                  style: styles.cellTitle
                                }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                                  children: "",
                                  style: styles.cellText
                                })), React.createElement(SpacedView$ReactMultiversal.make, {
                              vertical: /* None */7,
                              style: styles.cell,
                              children: null
                            }, React.createElement(ReactNative.Text, {
                                  children: "And more...",
                                  style: styles.cellTitle
                                }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                                  children: "!I am sure my knowledge and experiences might be useful to you in many ways.",
                                  style: styles.cellText
                                })))), React.createElement(Spacer$ReactMultiversal.make, {})), React.createElement(Container$ReactMultiversal.make, {
                  children: React.createElement(Skills.make, {})
                }));
}

var make = PageServices;

var $$default = PageServices;

export {
  styles ,
  make ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
