// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Head from "next/head";

function AppMeta(Props) {
  return React.createElement(Head, {
              children: null
            }, React.createElement("meta", {
                  charSet: "utf-8"
                }), React.createElement("link", {
                  href: "https://a.moox.fr",
                  rel: "dns-prefetch"
                }), React.createElement("link", {
                  href: "https://a.moox.fr",
                  rel: "preconnect"
                }), React.createElement("link", {
                  href: "/apple-touch-icon.png",
                  rel: "apple-touch-icon",
                  sizes: "180x180"
                }), React.createElement("link", {
                  href: "/favicon-32x32.png",
                  rel: "icon",
                  sizes: "32x32",
                  type: "image/png"
                }), React.createElement("link", {
                  href: "/favicon-16x16.png",
                  rel: "icon",
                  sizes: "16x16",
                  type: "image/png"
                }), React.createElement("link", {
                  href: "/site.webmanifest",
                  rel: "manifest"
                }), React.createElement("meta", {
                  content: "#01093C",
                  name: "msapplication-TileColor"
                }), React.createElement("meta", {
                  content: "#01093C",
                  name: "theme-color"
                }), React.createElement("meta", {
                  content: "width=device-width, initial-scale=1",
                  name: "viewport"
                }), React.createElement("style", {
                  dangerouslySetInnerHTML: {
                    __html: "@-ms-viewport { width: device-width } @viewport { width: device-width }"
                  }
                }), React.createElement("style", {
                  dangerouslySetInnerHTML: {
                    __html: "\n@font-face {\n  font-family: 'StoneHarbour';\n  src: url('/fonts/stoneharbour-webfont.woff2') format('woff2'),\n        url('/fonts/stoneharbour-webfont.woff') format('woff');\n  font-weight: normal;\n  font-style: normal;\n}\n@font-face {\n  font-family: 'StoneHarbourWash';\n  src: url('/fonts/stoneharbourswash-webfont.woff2') format('woff2'),\n        url('/fonts/stoneharbourswash-webfont.woff') format('woff');\n  font-weight: normal;\n  font-style: normal;\n}\n@font-face {\n  font-family: 'Phosphate';\n  src: url('/fonts/phosphateinline-webfont.woff2') format('woff2'),\n        url('/fonts/phosphateinline-webfont.woff') format('woff');\n  font-weight: normal;\n  font-style: normal;\n}\n\nhtml {\n  width: 100%;\n  height: 100%;\n  overflow-x:hidden;\n  background: #fff;\n}\nbody {\n  display: flex;\n  flex-grow: 1;\n  min-width: 100%;\n  min-height: 100%;\n  overflow-x: hidden;\n}\n\n#__next {\n  display: flex;\n  flex-grow: 1;\n}\n\n@supports(padding: max(0px)) {\n  body {\n    /* https://webkit.org/blog/7929/designing-websites-for-iphone-x/ */\n    padding-left: env(safe-area-inset-left);\n    padding-right: env(safe-area-inset-right);\n    /* padding-left: max(12px, env(safe-area-inset-left)); */\n    /* padding-right: max(12px, env(safe-area-inset-right)); */\n    padding-bottom: env(safe-area-inset-bottom);\n  }\n}\n\n@media (min-width: 500px) { .WindowSizeFilterSMax { display: none } }\n@media (max-width: 501px) { .WindowSizeFilterMMin { display: none } }\n\n.FixedBottom {\n  pointer-events: none;\n  z-index: 1000;\n  position: fixed;\n  left: 0;\n  right: 0;\n  bottom: 0;\n}\n\n.FixedBottom * {\n  pointer-events: all;\n}\n"
                  }
                }));
}

var make = AppMeta;

export {
  make ,
  
}
/* react Not a pure module */
