// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";

function Avatar(Props) {
  var size = Props.size;
  var borderWidthOpt = Props.borderWidth;
  var borderColorOpt = Props.borderColor;
  var uriOpt = Props.uri;
  var borderWidth = borderWidthOpt !== undefined ? borderWidthOpt : Predefined$ReactMultiversal.hairlineWidth;
  var borderColor = borderColorOpt !== undefined ? borderColorOpt : Predefined$ReactMultiversal.Colors.separator;
  var uri = uriOpt !== undefined ? uriOpt : "/avatar.jpg";
  var width = size - borderWidth * 2;
  var height = size - borderWidth * 2;
  return React.createElement(ReactNative.View, {
              style: {
                borderColor: borderColor,
                borderRadius: size,
                borderWidth: borderWidth,
                height: size,
                overflow: "hidden",
                width: size
              },
              children: React.createElement(ReactNative.Image, {
                    defaultSource: {
                      uri: uri,
                      width: width,
                      height: height
                    },
                    source: {
                      uri: uri,
                      width: width,
                      height: height
                    }
                  }),
              key: Predefined$ReactMultiversal.hairlineWidth.toString()
            });
}

var make = Avatar;

export {
  make ,
  
}
/* react Not a pure module */
