// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      background: {
        backgroundColor: "#FBFCF8",
        borderRadius: 6
      }
    });

function Background(Props) {
  var children = Props.children;
  return React.createElement(ReactNative.View, {
              style: styles.background,
              children: children
            });
}

var make = Background;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
