// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as SVGDeviceIphone from "../../assets/SVGs/components/SVGDeviceIphone.bs.js";
import * as Animated$ReactNative from "rescript-react-native/src/apis/Animated.bs.js";

var originalRatio = 788 / 389;

function DeviceIPhoneX(Props) {
  var s = Props.style;
  var width = Props.width;
  var children = Props.children;
  var backgroundColorOpt = Props.backgroundColor;
  var backgroundColor = backgroundColorOpt !== undefined ? backgroundColorOpt : "#fff";
  var height = width * originalRatio;
  return React.createElement(Animated$ReactNative.View.make, {
              style: [
                s,
                {
                  height: height,
                  width: width
                }
              ],
              children: null
            }, React.createElement(ReactNative.View, {
                  style: {
                    backgroundColor: backgroundColor,
                    borderRadius: width * 0.1,
                    flexGrow: 1,
                    flexShrink: 1,
                    margin: width * 0.05,
                    overflow: "hidden"
                  },
                  children: children
                }), React.createElement(ReactNative.View, {
                  pointerEvents: "none",
                  style: ReactNative.StyleSheet.absoluteFill,
                  children: React.createElement(SVGDeviceIphone.make, {
                        width: width,
                        height: height
                      })
                }));
}

var originalHeight = 788;

var originalWidth = 389;

var make = DeviceIPhoneX;

export {
  originalHeight ,
  originalWidth ,
  originalRatio ,
  make ,
  
}
/* react Not a pure module */
