// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center",
        justifyContent: "center"
      },
      oops: {
        color: "#ddd",
        fontSize: 64,
        lineHeight: 64,
        textAlign: "center"
      },
      title: {
        fontSize: 24,
        lineHeight: 48,
        textAlign: "center",
        margin: 60
      }
    });

function ErrorView(Props) {
  var label = Props.label;
  var errorText = label !== undefined ? label : "Shit happened!";
  return React.createElement(SpacedView$ReactMultiversal.make, {
              vertical: /* XXL */0,
              horizontal: /* None */7,
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: "Oooops!",
                  style: styles.oops
                }), React.createElement(ReactNative.View, {
                  children: React.createElement(ReactNative.Text, {
                        children: errorText,
                        style: styles.title
                      })
                }));
}

var make = ErrorView;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
