// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as TextLink from "./TextLink.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as SocialIcons from "./SocialIcons.bs.js";
import * as ReactNative from "react-native";
import * as Container$ReactMultiversal from "react-multiversal/src/Container.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var styles = ReactNative.StyleSheet.create({
      icon: {
        padding: 10
      },
      link: {
        color: "#FBFCF8",
        fontSize: 14,
        padding: 10
      },
      text: {
        color: "#FBFCF8",
        fontSize: 12,
        lineHeight: 20
      }
    });

function Footer(Props) {
  return React.createElement(ReactNative.View, {
              children: React.createElement(Container$ReactMultiversal.make, {
                    wrapperStyle: {
                      backgroundColor: Consts.Colors.dark
                    },
                    children: null
                  }, React.createElement(ReactNative.View, {
                        style: [
                          Predefined$ReactMultiversal.styles.rowWrap,
                          Predefined$ReactMultiversal.styles.flex,
                          Predefined$ReactMultiversal.styles.alignCenter
                        ],
                        children: null
                      }, React.createElement(SpacedView$ReactMultiversal.make, {
                            vertical: /* S */4,
                            horizontal: /* S */4,
                            children: React.createElement(SocialIcons.make, {
                                  wrapperStyle: Predefined$ReactMultiversal.styles.rowCenter,
                                  iconStyle: styles.icon,
                                  iconSize: 48
                                })
                          }), React.createElement(ReactNative.View, {
                            style: Predefined$ReactMultiversal.styles.flex
                          }), React.createElement(SpacedView$ReactMultiversal.make, {
                            vertical: /* S */4,
                            horizontal: /* S */4,
                            style: [
                              Predefined$ReactMultiversal.styles.rowWrap,
                              Predefined$ReactMultiversal.styles.flexShrink
                            ],
                            children: Belt_Array.map(Consts.menuLinks, (function (item) {
                                    return React.createElement(TextLink.make, {
                                                children: item.text,
                                                href: item.link,
                                                style: styles.link,
                                                key: item.link
                                              });
                                  }))
                          })), React.createElement(SpacedView$ReactMultiversal.make, {
                        vertical: /* L */2,
                        horizontal: /* L */2,
                        style: Predefined$ReactMultiversal.styles.rowWrap,
                        children: null
                      }, React.createElement(ReactNative.View, {
                            style: [
                              Predefined$ReactMultiversal.styles.rowWrap,
                              Predefined$ReactMultiversal.styles.flexShrink
                            ],
                            children: null
                          }, React.createElement(ReactNative.Text, {
                                children: "Made with ",
                                style: styles.text
                              }), React.createElement(TextLink.make, {
                                children: "ReScript, ",
                                href: "https://rescript-lang.org/",
                                style: styles.text
                              }), React.createElement(TextLink.make, {
                                children: "React Native",
                                href: "https://reactnative.dev",
                                style: styles.text
                              }), React.createElement(TextLink.make, {
                                children: " Web, ",
                                href: "https://necolas.github.io/react-native-web/",
                                style: styles.text
                              }), React.createElement(TextLink.make, {
                                children: "Next.js",
                                href: "https://nextjs.org",
                                style: styles.text
                              }), React.createElement(ReactNative.Text, {
                                children: " and ",
                                style: styles.text
                              }), React.createElement(TextLink.make, {
                                children: "ReScript React Native",
                                href: "https://rescript-react-native.github.io",
                                style: styles.text
                              })), React.createElement(ReactNative.Text, {
                            children: "  ·  ",
                            style: styles.text
                          }), React.createElement(TextLink.make, {
                            children: "100% Over-engineered source available on GitHub",
                            href: "https://github.com/MoOx/moox",
                            style: styles.text
                          })))
            });
}

var make = Footer;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
