// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ViewLink from "./ViewLink.bs.js";
import * as AppWrapper from "./AppWrapper.bs.js";
import * as SVGContact from "../../assets/SVGs/components/SVGContact.bs.js";
import * as ReactNative from "react-native";
import * as SVGChevronRight from "../../assets/SVGs/components/SVGChevronRight.bs.js";
import * as WindowSizeFilter from "./WindowSizeFilter.bs.js";
import * as Row$ReactMultiversal from "react-multiversal/src/Row.bs.js";
import * as StickyHeaderBackground from "./StickyHeaderBackground.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as StickyHeader$ReactMultiversal from "react-multiversal/src/StickyHeader.bs.js";

function HeaderSmall(Props) {
  var title = Props.title;
  var animateBackgroundOpacityOpt = Props.animateBackgroundOpacity;
  var getInTouchOpt = Props.getInTouch;
  var animateBackgroundOpacity = animateBackgroundOpacityOpt !== undefined ? animateBackgroundOpacityOpt : /* True */0;
  var getInTouch = getInTouchOpt !== undefined ? getInTouchOpt : true;
  return React.createElement(WindowSizeFilter.SMax.make, {
              children: React.createElement(StickyHeader$ReactMultiversal.make, {
                    scrollYAnimatedValue: AppWrapper.scrollYAnimatedValue,
                    title: title,
                    scrollOffsetY: 100,
                    right: (function (param) {
                        var color = param.color;
                        return React.createElement(React.Fragment, undefined, getInTouch ? React.createElement(ViewLink.make, {
                                          href: "/contact",
                                          children: React.createElement(Row$ReactMultiversal.Center.make, {
                                                children: null
                                              }, React.createElement(ReactNative.Text, {
                                                    children: "Get in touch",
                                                    style: {
                                                      color: color,
                                                      paddingBottom: 2
                                                    }
                                                  }), React.createElement(SVGChevronRight.make, {
                                                    width: 19,
                                                    height: 19,
                                                    fill: color
                                                  }))
                                        }) : React.createElement("a", {
                                          style: {
                                            textDecoration: "none"
                                          },
                                          href: "/MaximeThirouin.vcf"
                                        }, React.createElement(Row$ReactMultiversal.Center.make, {
                                              children: null
                                            }, React.createElement(ReactNative.Text, {
                                                  children: "Save",
                                                  style: {
                                                    color: color,
                                                    paddingBottom: 2
                                                  }
                                                }), React.createElement(Spacer$ReactMultiversal.make, {
                                                  size: /* XXS */6
                                                }), React.createElement(SVGContact.make, {
                                                  width: 19,
                                                  height: 19,
                                                  fill: color
                                                }))));
                      }),
                    color: "#fff",
                    color2: Predefined$ReactMultiversal.Colors.Ios.light.blue,
                    animateBackgroundOpacity: animateBackgroundOpacity,
                    backgroundElement: React.createElement(StickyHeaderBackground.make, {
                          backdropFilter: "saturate(200%) brightness(150%) grayscale(20%) blur(20px)",
                          style: {
                            backgroundColor: "rgba(255,255,255,0.8)",
                            bottom: 0,
                            left: 0,
                            position: "absolute",
                            right: 0,
                            top: 0
                          }
                        })
                  })
            });
}

var make = HeaderSmall;

export {
  make ,
  
}
/* react Not a pure module */
