// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      hugeText: {
        fontSize: 120,
        lineHeight: 120,
        display: "flex",
        flex: 1,
        justifyContent: "center",
        paddingVertical: 40
      }
    });

function Huge(Props) {
  var children = Props.children;
  return React.createElement(ReactNative.Text, {
              children: children,
              style: styles.hugeText
            });
}

var make = Huge;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
