// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ImageFromUri from "./ImageFromUri.bs.js";
import * as ReactNative from "react-native";
import * as PlaceholderWithAspectRatio from "./PlaceholderWithAspectRatio.bs.js";

var styles = ReactNative.StyleSheet.create({
      imageContainer: {
        display: "flex",
        overflow: "hidden"
      },
      image: {
        backgroundColor: "#eee",
        bottom: 0,
        left: 0,
        position: "absolute",
        right: 0,
        top: 0
      }
    });

function ImageWithAspectRatio(Props) {
  var uri = Props.uri;
  var ratio = Props.ratio;
  var styl = Props.style;
  return React.createElement(ReactNative.View, {
              style: styles.imageContainer,
              children: React.createElement(PlaceholderWithAspectRatio.make, {
                    ratio: ratio,
                    children: React.createElement(ImageFromUri.make, {
                          uri: uri,
                          style: [
                            Caml_option.some(styles.image),
                            styl
                          ]
                        })
                  })
            });
}

var make = ImageWithAspectRatio;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
