// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Font from "./shareable/Font.bs.js";
import * as Theme from "./shareable/Theme.bs.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as SVGLogo from "../../assets/SVGs/components/SVGLogo.bs.js";
import $$Image from "next/image";
import * as ReactNative from "react-native";
import * as WindowSizeFilter from "./WindowSizeFilter.bs.js";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as SvgFilterTurbulence from "./SvgFilterTurbulence.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as GradientLinearBackground from "./shareable/GradientLinearBackground.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        minHeight: 450
      },
      content: {
        flex: 1,
        justifyContent: "center"
      },
      subtitle: {
        color: Consts.Colors.light,
        fontSize: 18.5,
        fontWeight: "200"
      }
    });

function JumbotronCreativeDeveloper(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(SvgFilterTurbulence.make, {
                  id: "JumbotronCreativeDeveloperSVGFilter1",
                  baseFrequency: "0.05",
                  numOctaves: "5",
                  seed: "4",
                  saturate: "50",
                  scale: "4"
                }), React.createElement(SvgFilterTurbulence.make, {
                  id: "JumbotronCreativeDeveloperSVGFilter2",
                  baseFrequency: "0.04",
                  numOctaves: "5",
                  seed: "4",
                  saturate: "50",
                  scale: "4"
                }), React.createElement(SvgFilterTurbulence.make, {
                  id: "JumbotronCreativeDeveloperSVGFilter4",
                  baseFrequency: "0.03",
                  numOctaves: "5",
                  seed: "4",
                  saturate: "50",
                  scale: "4"
                }), React.createElement(SvgFilterTurbulence.make, {
                  id: "JumbotronCreativeDeveloperSVGFilter5",
                  baseFrequency: "0.045",
                  numOctaves: "5",
                  seed: "4",
                  saturate: "50",
                  scale: "4"
                }), React.createElement(SvgFilterTurbulence.make, {
                  id: "JumbotronCreativeDeveloperSVGFilter5",
                  baseFrequency: "0.045",
                  numOctaves: "7",
                  seed: "4",
                  saturate: "50",
                  scale: "4"
                }), React.createElement("style", {
                  dangerouslySetInnerHTML: {
                    __html: "\n@keyframes JumbotronCreativeDeveloperSVGFilterAnimation {\n  0% { filter: url(#JumbotronCreativeDeveloperSVGFilter1); }\n  20% { filter: url(#JumbotronCreativeDeveloperSVGFilter2); }\n  40% { filter: url(#JumbotronCreativeDeveloperSVGFilter3); }\n  60% { filter: url(#JumbotronCreativeDeveloperSVGFilter4); }\n  80% { filter: url(#JumbotronCreativeDeveloperSVGFilter5); }\n  100% { filter: url(#JumbotronCreativeDeveloperSVGFilter6); }\n}"
                  }
                }), React.createElement(ReactNative.View, {
                  style: styles.container,
                  children: null
                }, React.createElement(ReactNative.View, {
                      style: [
                        ReactNative.StyleSheet.absoluteFill,
                        {
                          transform: [
                            {
                              rotate: Style$ReactNative.deg(-3)
                            },
                            {
                              scale: 1.1
                            }
                          ],
                          overflow: "hidden"
                        },
                        {
                          background: "linear-gradient(16deg, #f430a9, #f2e782)"
                        }
                      ]
                    }), React.createElement(ReactNative.View, {
                      style: [
                        {
                          justifyContent: "flex-end",
                          left: Style$ReactNative.pct(25),
                          position: "absolute",
                          top: 60
                        },
                        {
                          mixBlendMode: "screen",
                          filter: "grayscale(100%) contrast(2)"
                        }
                      ],
                      children: React.createElement($$Image, {
                            height: 350,
                            objectFit: "contain",
                            src: "/me-with-hand-mic.png",
                            width: 350
                          })
                    }), React.createElement(ReactNative.View, {
                      style: [
                        ReactNative.StyleSheet.absoluteFill,
                        Predefined$ReactMultiversal.styles.rowCenter
                      ],
                      children: null
                    }, React.createElement(WindowSizeFilter.MMin.make, {
                          children: React.createElement(ReactNative.View, {
                                style: {
                                  opacity: 0.06,
                                  transform: [{
                                      rotate: Style$ReactNative.deg(6)
                                    }],
                                  position: "absolute",
                                  right: -20,
                                  top: -30
                                },
                                children: React.createElement(SVGLogo.make, {
                                      width: 240,
                                      height: 240,
                                      fill: Consts.Colors.lightest
                                    })
                              })
                        }), React.createElement("div", {
                          style: {
                            height: "1px",
                            width: "5%"
                          }
                        }), React.createElement(WindowSizeFilter.MMin.make, {
                          style: {
                            height: "1px",
                            width: "35%"
                          }
                        }), React.createElement(ReactNative.View, {
                          accessibilityRole: "header",
                          style: styles.content,
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "MoOx",
                              style: [
                                Font.androidEm.headline3,
                                {
                                  color: Theme.Default.colors.dark.text
                                },
                                {
                                  filter: "url(#JumbotronCreativeDeveloperSVGFilter1)"
                                }
                              ]
                            }), React.createElement(ReactNative.Text, {
                              children: "Maxime Thirouin",
                              style: styles.subtitle
                            }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(GradientLinearBackground.make, {
                              style: {
                                borderRadius: 6
                              },
                              stops: [
                                {
                                  offset: Style$ReactNative.pct(0),
                                  stopColor: "#fff",
                                  stopOpacity: "1"
                                },
                                {
                                  offset: Style$ReactNative.pct(100),
                                  stopColor: "#fff",
                                  stopOpacity: "0"
                                }
                              ],
                              angle: 90,
                              children: React.createElement(SpacedView$ReactMultiversal.make, {
                                    children: null
                                  }, React.createElement(ReactNative.Text, {
                                        children: "Creative Developer",
                                        style: [
                                          Font.android.headline3,
                                          Font.weight.bold,
                                          {
                                            filter: "drop-shadow(1px 1px 1px rgba(0,0,0,0.5)) drop-shadow(2px 6px 6px rgba(254,167,183,0.22))",
                                            backgroundClip: "text",
                                            WebkitTextFillColor: "transparent",
                                            backgroundImage: "linear-gradient(0deg, #792F93 0%, #000064 80%)"
                                          }
                                        ]
                                      }), React.createElement(ReactNative.View, {
                                        style: [
                                          Predefined$ReactMultiversal.styles.row,
                                          {
                                            alignItems: "center"
                                          }
                                        ],
                                        children: null
                                      }, React.createElement(ReactNative.Text, {
                                            children: "For ",
                                            style: [Font.weight[200]]
                                          }), React.createElement(ReactNative.View, {
                                            style: {
                                              transform: [{
                                                  rotate: Style$ReactNative.deg(-6)
                                                }]
                                            },
                                            children: React.createElement(ReactNative.Text, {
                                                  children: "Creative People",
                                                  style: [
                                                    Font.android.headline3,
                                                    Object.assign({}, {
                                                          color: "#fff",
                                                          fontFamily: "StoneHarbour"
                                                        }, {
                                                          filter: "drop-shadow(1px 1px 0px rgba(0,0,0,0.25)) drop-shadow(2px 6px 6px rgba(254,167,183,0.22))",
                                                          backgroundClip: "text",
                                                          WebkitTextFillColor: "transparent",
                                                          backgroundImage: "linear-gradient(0deg, #F451C8 0%, #EACE5E 80%)"
                                                        })
                                                  ]
                                                })
                                          })))
                            })))));
}

var make = JumbotronCreativeDeveloper;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
