// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ViewLink from "./ViewLink.bs.js";
import * as SVGSpeechBubble from "../../assets/SVGs/components/SVGSpeechBubble.bs.js";
import * as WindowSizeFilter from "./WindowSizeFilter.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";
import * as FixedBottom$ReactMultiversal from "react-multiversal/src/FixedBottom.bs.js";
import * as TabBarWrapper$ReactMultiversal from "react-multiversal/src/TabBarWrapper.bs.js";
import * as ButtonContained$ReactMultiversal from "react-multiversal/src/ButtonContained.bs.js";

function LinkContactBubbleFixedBottom(Props) {
  return React.createElement(FixedBottom$ReactMultiversal.make, {
              children: null
            }, React.createElement(SpacedView$ReactMultiversal.make, {
                  style: {
                    alignSelf: "flex-end"
                  },
                  children: React.createElement(ViewLink.make, {
                        href: "/contact/",
                        children: React.createElement(ButtonContained$ReactMultiversal.make, {
                              round: true,
                              color: Predefined$ReactMultiversal.Colors.Ios.light.green,
                              horizontalSpace: /* S */4,
                              verticalSpace: /* S */4,
                              children: React.createElement(SVGSpeechBubble.make, {
                                    width: 24,
                                    height: 24,
                                    fill: Predefined$ReactMultiversal.Colors.white
                                  })
                            })
                      })
                }), React.createElement(WindowSizeFilter.SMax.make, {
                  children: React.createElement(TabBarWrapper$ReactMultiversal.Placeholder.make, {})
                }));
}

var make = LinkContactBubbleFixedBottom;

export {
  make ,
  
}
/* react Not a pure module */
