// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        justifyContent: "center"
      }
    });

function LoadingIndicator(Props) {
  return React.createElement(SpacedView$ReactMultiversal.make, {
              vertical: /* XXL */0,
              horizontal: /* None */7,
              children: React.createElement(ReactNative.ActivityIndicator, {
                    size: "large"
                  })
            });
}

var make = LoadingIndicator;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
