// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var uri = "/me-bg.jpg";

var w = 1750 / 2;

var h = 850 / 2;

function MeBackground(Props) {
  var styl = Props.style;
  return React.createElement(ReactNative.Image, {
              defaultSource: {
                uri: uri,
                width: w,
                height: h
              },
              source: {
                uri: uri,
                width: w,
                height: h
              },
              style: [
                {
                  height: h,
                  width: w
                },
                styl
              ]
            });
}

var make = MeBackground;

export {
  uri ,
  w ,
  h ,
  make ,
  
}
/* react Not a pure module */
