// Generated by ReScript, PLEASE EDIT WITH CARE

import * as T from "../T.bs.js";
import * as Font from "./shareable/Font.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";
import * as UnderlinedTextLink from "./UnderlinedTextLink.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

var styles = ReactNative.StyleSheet.create({
      block: {
        flex: 1,
        flexDirection: "row"
      },
      text: {
        color: Consts.Colors.dark,
        lineHeight: 28,
        alignItems: "flex-start",
        flex: 1,
        flexDirection: "row"
      },
      title: {
        fontSize: 22
      }
    });

function PostPreview(Props) {
  var item = Props.item;
  var theme = Curry._2(T.useTheme, undefined, undefined);
  var href = "/blog/" + (item.id + "/");
  var lang = item.lang;
  return React.createElement(SpacedView$ReactMultiversal.make, {
              horizontal: /* None */7,
              children: React.createElement(ReactNative.Text, {
                    children: null,
                    style: [
                      Font.ios.title3,
                      theme.styles.text
                    ]
                  }, React.createElement(ReactNative.Text, {
                        children: "•"
                      }), React.createElement(Spacer$ReactMultiversal.make, {
                        size: /* S */4
                      }), React.createElement(UnderlinedTextLink.make, {
                        href: href,
                        style: styles.title,
                        children: Belt_Option.getWithDefault(Caml_option.null_to_opt(item.title), "...")
                      }), React.createElement(Spacer$ReactMultiversal.make, {
                        size: /* S */4
                      }), lang !== null ? React.createElement(ReactNative.Text, {
                          children: "[" + (lang + "] ")
                        }) : null),
              key: item.id
            });
}

var make = PostPreview;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
