// Generated by ReScript, PLEASE EDIT WITH CARE

import * as T from "../T.bs.js";
import * as Font from "./shareable/Font.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as SVGReact from "../../assets/SVGs/components/SVGReact.bs.js";
import * as ViewLink from "./ViewLink.bs.js";
import * as SVGDevCss from "../../assets/SVGs/components/SVGDevCss.bs.js";
import * as SVGDevPhp from "../../assets/SVGs/components/SVGDevPhp.bs.js";
import * as SVGSketch from "../../assets/SVGs/components/SVGSketch.bs.js";
import * as SVGDevHtml from "../../assets/SVGs/components/SVGDevHtml.bs.js";
import * as SVGDevices from "../../assets/SVGs/components/SVGDevices.bs.js";
import * as ReactNative from "react-native";
import * as SVGDevRescript from "../../assets/SVGs/components/SVGDevRescript.bs.js";
import * as SVGDevPhotoshop from "../../assets/SVGs/components/SVGDevPhotoshop.bs.js";
import * as SVGDevWordpress from "../../assets/SVGs/components/SVGDevWordpress.bs.js";
import * as SVGAppStoreApple from "../../assets/SVGs/components/SVGAppStoreApple.bs.js";
import * as SVGDevJavascript from "../../assets/SVGs/components/SVGDevJavascript.bs.js";
import * as SVGDevTypescript from "../../assets/SVGs/components/SVGDevTypescript.bs.js";
import * as SVGAppStoreGoogle from "../../assets/SVGs/components/SVGAppStoreGoogle.bs.js";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as Row$ReactMultiversal from "react-multiversal/src/Row.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as GradientLinearBackground from "./shareable/GradientLinearBackground.bs.js";
import * as SVGArrowRoundedWithTailTop from "../../assets/SVGs/components/SVGArrowRoundedWithTailTop.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

function ScreenHome(Props) {
  var themeModeOpt = Props.theme;
  var themeMode = themeModeOpt !== undefined ? themeModeOpt : "auto";
  var theme = Curry._2(T.useTheme, themeMode, undefined);
  return React.createElement(React.Fragment, undefined, React.createElement(SpacedView$ReactMultiversal.make, {
                  vertical: /* None */7,
                  children: null
                }, React.createElement(ViewLink.make, {
                      href: "/resume/",
                      children: React.createElement(GradientLinearBackground.make, {
                            style: {
                              borderRadius: 6,
                              overflow: "hidden"
                            },
                            stops: [
                              {
                                offset: Style$ReactNative.pct(0),
                                stopColor: "#00d2ff",
                                stopOpacity: "1"
                              },
                              {
                                offset: Style$ReactNative.pct(100),
                                stopColor: "#792F93",
                                stopOpacity: "1"
                              }
                            ],
                            children: null
                          }, React.createElement(SpacedView$ReactMultiversal.make, {
                                children: null
                              }, React.createElement(ReactNative.View, {
                                    style: {
                                      opacity: 0.1,
                                      transform: [
                                        {
                                          perspective: 800
                                        },
                                        {
                                          rotate: Style$ReactNative.deg(6)
                                        }
                                      ],
                                      bottom: -50,
                                      position: "absolute",
                                      right: -40
                                    },
                                    children: React.createElement(SVGReact.make, {
                                          width: 200,
                                          height: 200,
                                          fill: Consts.Colors.light
                                        })
                                  }), React.createElement(ReactNative.Text, {
                                    children: "I MAKE",
                                    style: [
                                      Font.ios.title3,
                                      T.stylesDark.text
                                    ]
                                  }), React.createElement(ReactNative.Text, {
                                    children: "Apps & Websites",
                                    style: [
                                      Font.iosEm.largeTitle,
                                      T.stylesDark.text
                                    ]
                                  }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                                    children: "Web or Native ? It can also be both !",
                                    style: [
                                      Font.ios.title3,
                                      T.stylesDark.text
                                    ]
                                  }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                                    children: "Do you have such a need ? If so contact me !",
                                    style: [
                                      Font.ios.body,
                                      T.stylesDark.text
                                    ]
                                  }), React.createElement(Spacer$ReactMultiversal.make, {})), React.createElement(SpacedView$ReactMultiversal.make, {
                                style: {
                                  backgroundColor: "#00d2ff",
                                  borderBottomLeftRadius: 4,
                                  borderBottomRightRadius: 4,
                                  flexDirection: "row"
                                },
                                children: null
                              }, React.createElement(SVGDevices.make, {
                                    width: 42,
                                    height: 42,
                                    fill: Consts.Colors.lightGrey
                                  }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                                    children: "Mobile & Desktop",
                                    style: [
                                      Font.ios.largeTitle,
                                      T.stylesDark.text
                                    ]
                                  })))
                    }), React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* L */2
                    }), React.createElement(ViewLink.make, {
                      href: "/resume/",
                      children: null
                    }, React.createElement(ReactNative.Text, {
                          children: "Need help for your project?".toUpperCase(),
                          style: [
                            Font.ios.subhead,
                            theme.styles.textLight1
                          ]
                        }), React.createElement(Row$ReactMultiversal.SpaceBetween.make, {
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "I can help you",
                              style: [
                                Font.iosEm.title1,
                                theme.styles.text
                              ]
                            }), React.createElement(ReactNative.View, {
                              style: {
                                transform: [{
                                    rotate: Style$ReactNative.deg(90)
                                  }]
                              },
                              children: React.createElement(SVGArrowRoundedWithTailTop.make, {
                                    width: 20,
                                    height: 20,
                                    fill: theme.colors.text
                                  })
                            }))), React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* S */4
                    }), React.createElement(ReactNative.View, {
                      style: Predefined$ReactMultiversal.styles.rowWrapCenter,
                      children: null
                    }, React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevHtml.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevCss.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevJavascript.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevTypescript.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          style: Predefined$ReactMultiversal.styles.center,
                          children: React.createElement(SVGDevPhp.make, {
                                width: 256 / 4,
                                height: 136 / 4
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevWordpress.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevPhotoshop.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGSketch.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGAppStoreApple.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGAppStoreGoogle.make, {
                                width: 64,
                                height: 64
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGReact.make, {
                                width: 64,
                                height: 64,
                                fill: "#61dafb"
                              })
                        }), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* XS */5,
                          horizontal: /* XS */5,
                          children: React.createElement(SVGDevRescript.make, {
                                width: 64,
                                height: 64
                              })
                        }))));
}

var make = ScreenHome;

export {
  make ,
  
}
/* T Not a pure module */
