// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as ViewLink from "./ViewLink.bs.js";
import * as ReactNative from "react-native";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as Row$ReactMultiversal from "react-multiversal/src/Row.bs.js";
import * as Title$ReactMultiversal from "react-multiversal/src/Title.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as TitlePre$ReactMultiversal from "react-multiversal/src/TitlePre.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";
import * as ButtonContained$ReactMultiversal from "react-multiversal/src/ButtonContained.bs.js";

function ScreenAppInSearch(Props) {
  return React.createElement(SpacedView$ReactMultiversal.make, {
              children: null
            }, React.createElement(Title$ReactMultiversal.make, {
                  children: null
                }, React.createElement(ReactNative.Text, {
                      children: "G",
                      style: {
                        color: "#356FEF"
                      }
                    }), React.createElement(ReactNative.Text, {
                      children: "o",
                      style: {
                        color: "#E22C28"
                      }
                    }), React.createElement(ReactNative.Text, {
                      children: "g",
                      style: {
                        color: "#FBB10D"
                      }
                    }), React.createElement(ReactNative.Text, {
                      children: "g",
                      style: {
                        color: "#356FEF"
                      }
                    }), React.createElement(ReactNative.Text, {
                      children: "l",
                      style: {
                        color: "#2B9C40"
                      }
                    }), React.createElement(ReactNative.Text, {
                      children: "e",
                      style: {
                        color: "#E22C28"
                      }
                    }), React.createElement(ReactNative.Text, {
                      children: "s",
                      style: {
                        color: "#FBB10D"
                      }
                    })), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(Row$ReactMultiversal.make, {
                  children: null
                }, React.createElement(ReactNative.TextInput, {
                      defaultValue: "your product",
                      style: {
                        borderColor: Consts.Colors.lightGrey,
                        borderRadius: 10,
                        borderStyle: "solid",
                        borderWidth: 1,
                        padding: Spacer$ReactMultiversal.space / 2,
                        width: Style$ReactNative.pct(90)
                      }
                    }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ViewLink.make, {
                      href: "/contact/",
                      children: React.createElement(ButtonContained$ReactMultiversal.make, {
                            round: true,
                            color: "#1F5EDC",
                            verticalSpace: /* XS */5,
                            children: React.createElement(ButtonContained$ReactMultiversal.$$Text.make, {
                                  children: "GO"
                                })
                          })
                    })), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                  children: "Your website",
                  style: {
                    color: "#356FEF",
                    fontSize: 22,
                    textDecorationLine: "underline"
                  }
                }), React.createElement(ReactNative.Text, {
                  children: "⭑⭑⭑⭑⭑",
                  style: {
                    color: "orange",
                    fontSize: 18,
                    fontWeight: "600"
                  }
                }), React.createElement(ReactNative.Text, {
                  children: "You need an awesome website that is fast & appear in search results? You got lucky, I can help.",
                  style: {
                    color: "#333",
                    fontSize: 14,
                    fontWeight: "300"
                  }
                }), React.createElement(Spacer$ReactMultiversal.make, {
                  size: /* S */4
                }), React.createElement(Row$ReactMultiversal.make, {
                  children: null
                }, React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.View, {
                      style: {
                        flex: 1
                      },
                      children: null
                    }, React.createElement(ReactNative.Text, {
                          children: "Fast",
                          style: {
                            color: "#356FEF",
                            fontSize: 20,
                            textDecorationLine: "underline"
                          }
                        }), React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* XS */5
                        }), React.createElement(ReactNative.Text, {
                          children: "I know how to build fast & beautiful webapps in all browsers.",
                          style: {
                            color: "#333",
                            fontSize: 14,
                            fontWeight: "300"
                          }
                        })), React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* S */4
                    }), React.createElement(ReactNative.View, {
                      style: {
                        flex: 1
                      },
                      children: null
                    }, React.createElement(ReactNative.Text, {
                          children: "Beautiful",
                          style: {
                            color: "#356FEF",
                            fontSize: 20,
                            textDecorationLine: "underline"
                          }
                        }), React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* XS */5
                        }), React.createElement(ReactNative.Text, {
                          children: "I can make your websites looking good without compromise.",
                          style: {
                            color: "#333",
                            fontSize: 14,
                            fontWeight: "300"
                          }
                        }))), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                  children: "Competitor website",
                  style: {
                    color: "#356FEF",
                    fontSize: 22,
                    textDecorationLine: "underline"
                  }
                }), React.createElement(ReactNative.Text, {
                  children: null,
                  style: {
                    color: "orange",
                    fontSize: 18,
                    fontWeight: "600"
                  }
                }, "⭑", React.createElement(ReactNative.Text, {
                      children: "⭑⭑⭑⭑",
                      style: {
                        color: Consts.Colors.lightGrey
                      }
                    })), React.createElement(ReactNative.Text, {
                  children: "Search engines measures performances. That's a fact.",
                  style: {
                    color: "#333",
                    fontSize: 14,
                    fontWeight: "300"
                  }
                }), React.createElement(Spacer$ReactMultiversal.make, {
                  size: /* S */4
                }), React.createElement(Row$ReactMultiversal.make, {
                  children: null
                }, React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.View, {
                      style: {
                        flex: 1
                      },
                      children: null
                    }, React.createElement(ReactNative.Text, {
                          children: "SEO",
                          style: {
                            color: "#356FEF",
                            fontSize: 20,
                            textDecorationLine: "underline"
                          }
                        }), React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* XS */5
                        }), React.createElement(ReactNative.Text, {
                          children: "Your sites & apps need to be fast, I know how to make it them fast.",
                          style: {
                            color: "#333",
                            fontSize: 14,
                            fontWeight: "300"
                          }
                        })), React.createElement(Spacer$ReactMultiversal.make, {
                      size: /* S */4
                    }), React.createElement(ReactNative.View, {
                      style: {
                        flex: 1
                      },
                      children: null
                    }, React.createElement(ReactNative.Text, {
                          children: "User experience",
                          style: {
                            color: "#356FEF",
                            fontSize: 20,
                            textDecorationLine: "underline"
                          }
                        }), React.createElement(Spacer$ReactMultiversal.make, {
                          size: /* XS */5
                        }), React.createElement(ReactNative.Text, {
                          children: "It needs to be polished. I can handle that for you.",
                          style: {
                            color: "#333",
                            fontSize: 14,
                            fontWeight: "300"
                          }
                        }))), React.createElement(Spacer$ReactMultiversal.make, {
                  size: /* L */2
                }), React.createElement(TitlePre$ReactMultiversal.make, {
                  children: "You are looking for something"
                }), React.createElement(Title$ReactMultiversal.make, {
                  children: "Here is a joke for you"
                }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.Text, {
                  children: "An engineer walks into a CSS codebase, he asks \"can you make this button green?\"\nCodebase replies: \"Can you be more specific?\"\nEngineer: but it's kind of !important\"",
                  style: {
                    color: "#333",
                    fontSize: 14,
                    fontWeight: "300",
                    lineHeight: 14 * 1.5
                  }
                }));
}

var make = ScreenAppInSearch;

export {
  make ,
  
}
/* react Not a pure module */
