// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SVGUi from "../../assets/SVGs/components/SVGUi.bs.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as SVGReact from "../../assets/SVGs/components/SVGReact.bs.js";
import * as SVGTouch from "../../assets/SVGs/components/SVGTouch.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNative from "react-native";
import * as SVGSocialGithub from "../../assets/SVGs/components/SVGSocialGithub.bs.js";
import * as CardWithGradient from "./CardWithGradient.bs.js";
import * as SVGJavaScriptMini from "../../assets/SVGs/components/SVGJavaScriptMini.bs.js";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as SVGDevRescriptIcon from "../../assets/SVGs/components/SVGDevRescriptIcon.bs.js";

var styles = ReactNative.StyleSheet.create({
      container: {
        alignItems: "center",
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center"
      },
      icon: {
        opacity: 0.1,
        transform: [
          {
            perspective: 800
          },
          {
            rotate: Style$ReactNative.deg(6)
          }
        ],
        bottom: -20,
        position: "absolute",
        right: -20
      }
    });

var skills = [
  {
    title: "JavaScript",
    text: "ES20** + Flow / TypeScript",
    color: Consts.Colors.light,
    bg: "#000B28",
    bg2: Consts.Colors.dark,
    icon: React.createElement(ReactNative.View, {
          style: styles.icon,
          children: React.createElement(SVGJavaScriptMini.make, {
                width: 170,
                height: 170,
                fill: Consts.Colors.light
              })
        })
  },
  {
    title: "React",
    text: "Web or Native... or both!",
    color: Consts.Colors.light,
    bg: "#09274F",
    bg2: Consts.Colors.dark,
    icon: React.createElement(ReactNative.View, {
          style: [
            styles.icon,
            {
              bottom: -40,
              right: -40
            }
          ],
          children: React.createElement(SVGReact.make, {
                width: 200,
                height: 200,
                fill: Consts.Colors.light
              })
        })
  },
  {
    title: "ReScript",
    text: "≃ Fully Typed JavaScript ♥",
    color: Consts.Colors.light,
    bg: "#035A93",
    bg2: Consts.Colors.dark,
    icon: React.createElement(ReactNative.View, {
          style: [
            styles.icon,
            {
              bottom: -40,
              right: -40
            }
          ],
          children: React.createElement(SVGDevRescriptIcon.make, {
                width: 200,
                height: 200,
                fill: Consts.Colors.light
              })
        })
  },
  {
    title: "Front-End",
    text: "I care about UI and UX",
    color: Consts.Colors.light,
    bg: "#28416A",
    bg2: Consts.Colors.dark,
    icon: React.createElement(ReactNative.View, {
          style: [
            styles.icon,
            {
              bottom: -30,
              right: -30
            }
          ],
          children: React.createElement(SVGTouch.make, {
                width: 200,
                height: 200,
                fill: Consts.Colors.light
              })
        })
  },
  {
    title: "Best Practices",
    text: "Git, Reviews, Tests...",
    color: Consts.Colors.light,
    bg: "#0FA5AE",
    bg2: Consts.Colors.dark,
    icon: React.createElement(ReactNative.View, {
          style: styles.icon,
          children: React.createElement(SVGUi.make, {
                width: 180,
                height: 180,
                fill: Consts.Colors.light
              })
        })
  },
  {
    title: "Open Source",
    text: "Sharing is caring",
    color: Consts.Colors.light,
    bg: "#36E9BE",
    bg2: Consts.Colors.dark,
    icon: React.createElement(ReactNative.View, {
          style: styles.icon,
          children: React.createElement(SVGSocialGithub.make, {
                width: 200,
                height: 200,
                fill: Consts.Colors.light
              })
        })
  }
];

function Skills(Props) {
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: Belt_Array.map(skills, (function (skill) {
                      return React.createElement(CardWithGradient.make, {
                                  item: skill,
                                  key: skill.title
                                });
                    }))
            });
}

var make = Skills;

export {
  styles ,
  skills ,
  make ,
  
}
/* styles Not a pure module */
