// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Consts from "../Consts.bs.js";
import * as ViewLink from "./ViewLink.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";

function SocialIcons(Props) {
  var wrapperStyle = Props.wrapperStyle;
  var iconStyle = Props.iconStyle;
  var iconColorOpt = Props.iconColor;
  var iconSizeOpt = Props.iconSize;
  var iconWrapperFuncOpt = Props.iconWrapperFunc;
  var iconColor = iconColorOpt !== undefined ? iconColorOpt : Consts.Colors.lightest;
  var iconSize = iconSizeOpt !== undefined ? iconSizeOpt : 16;
  var iconWrapperFunc = iconWrapperFuncOpt !== undefined ? iconWrapperFuncOpt : (function (children) {
        return children;
      });
  return React.createElement(ReactNative.View, {
              style: wrapperStyle,
              children: Belt_Array.map(Consts.socialLinks, (function (item) {
                      var tmp = {
                        accessibilityLabel: item.alt,
                        href: item.link,
                        children: Curry._1(iconWrapperFunc, Curry._2(item.componentFunc, iconColor, iconSize)),
                        key: item.link
                      };
                      if (iconStyle !== undefined) {
                        tmp.style = Caml_option.valFromOption(iconStyle);
                      }
                      return React.createElement(ViewLink.make, tmp);
                    }))
            });
}

var make = SocialIcons;

export {
  make ,
  
}
/* react Not a pure module */
