// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";

function StickyHeaderBackground(Props) {
  var backdropFilter = Props.backdropFilter;
  var s = Props.style;
  var children = Props.children;
  return ReactNative.unstable_createElement("div", {
              style: [
                s,
                Belt_Option.map(backdropFilter, (function (f) {
                        return {
                                WebkitBackdropFilter: f,
                                backdropFilter: f
                              };
                      }))
              ]
            }, children);
}

var make = StickyHeaderBackground;

export {
  make ,
  
}
/* react-native Not a pure module */
