// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SvgFilterTurbulence(Props) {
  var id = Props.id;
  var baseFrequencyOpt = Props.baseFrequency;
  var numOctavesOpt = Props.numOctaves;
  var seedOpt = Props.seed;
  var saturateOpt = Props.saturate;
  var scaleOpt = Props.scale;
  var baseFrequency = baseFrequencyOpt !== undefined ? baseFrequencyOpt : "0.05 0.05";
  var numOctaves = numOctavesOpt !== undefined ? numOctavesOpt : "2";
  var seed = seedOpt !== undefined ? seedOpt : "2";
  var saturate = saturateOpt !== undefined ? saturateOpt : "10";
  var scale = scaleOpt !== undefined ? scaleOpt : "5";
  return React.createElement("svg", {
              height: "0",
              width: "0"
            }, React.createElement("filter", {
                  id: id
                }, React.createElement("feTurbulence", {
                      type: "turbulence",
                      baseFrequency: baseFrequency,
                      numOctaves: numOctaves,
                      result: "turbulence",
                      seed: seed,
                      stitchTiles: "stitch"
                    }), React.createElement("feColorMatrix", {
                      type: "saturate",
                      in: "turbulence",
                      result: "colormatrix",
                      values: saturate
                    }), React.createElement("feComposite", {
                      in: "SourceGraphic",
                      in2: "colormatrix",
                      operator: "in",
                      result: "composite"
                    }), React.createElement("feDisplacementMap", {
                      in: "SourceGraphic",
                      in2: "colormatrix",
                      result: "displacementMap",
                      scale: scale,
                      xChannelSelector: "R",
                      yChannelSelector: "A"
                    })));
}

var make = SvgFilterTurbulence;

export {
  make ,
  
}
/* react Not a pure module */
