// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactNative from "react-native";

var coef = 2 * 0.8660254;

function Triangle(Props) {
  var hOpt = Props.height;
  var colour = Props.color;
  var styl = Props.style;
  var h = hOpt !== undefined ? hOpt : 50;
  return React.createElement(ReactNative.View, {
              style: [
                {
                  borderBottomColor: colour,
                  borderBottomWidth: h,
                  borderLeftColor: "transparent",
                  borderLeftWidth: h / coef,
                  borderRightColor: "transparent",
                  borderRightWidth: h / coef,
                  borderTopColor: "transparent",
                  borderTopWidth: 0,
                  height: 0,
                  width: 0
                },
                styl
              ]
            });
}

var make = Triangle;

export {
  coef ,
  make ,
  
}
/* react Not a pure module */
