// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TextLink from "./TextLink.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      link: {
        textDecorationLine: "underline",
        textDecorationStyle: "solid"
      }
    });

function UnderlinedTextLink(Props) {
  var href = Props.href;
  var styl = Props.style;
  var children = Props.children;
  return React.createElement(TextLink.make, {
              children: children,
              href: href,
              style: [
                Caml_option.some(styles.link),
                styl
              ]
            });
}

var make = UnderlinedTextLink;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
