// Generated by ReScript, PLEASE EDIT WITH CARE

import * as T from "../T.bs.js";
import * as Font from "./shareable/Font.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Avatar from "./Avatar.bs.js";
import * as Consts from "../Consts.bs.js";
import * as TextLink from "./TextLink.bs.js";
import * as ViewLink from "./ViewLink.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNative from "react-native";
import * as Style$ReactNative from "rescript-react-native/src/apis/Style.bs.js";
import * as SVGFlashyTriangle3 from "../../assets/SVGs/components/SVGFlashyTriangle3.bs.js";
import * as Spacer$ReactMultiversal from "react-multiversal/src/Spacer.bs.js";
import * as Predefined$ReactMultiversal from "react-multiversal/src/Predefined.bs.js";
import * as SpacedView$ReactMultiversal from "react-multiversal/src/SpacedView.bs.js";

function WebsiteFooter(Props) {
  var theme = Curry._2(T.useTheme, undefined, undefined);
  return React.createElement(ReactNative.View, {
              style: {
                transform: [{
                    translateZ: "0px"
                  }]
              },
              children: null
            }, React.createElement(ReactNative.View, {
                  style: Object.assign({}, {
                        height: 400
                      }, {
                        backgroundImage: "linear-gradient(rgba(118, 28, 174, 0) 0%, rgba(118, 28, 174, 1) 100%)"
                      })
                }), React.createElement(ReactNative.View, {
                  style: {
                    alignItems: "center",
                    height: 400 + 120,
                    justifyContent: "flex-end",
                    left: 0,
                    position: "absolute",
                    right: 0,
                    top: 0
                  },
                  children: React.createElement("img", {
                        alt: "",
                        src: "/_/landscape-sun.svg",
                        width: "500"
                      })
                }), React.createElement(ReactNative.View, {
                  style: Object.assign({}, {
                        height: 140
                      }, {
                        background: "#01093C url(/_/landscape-floor.png) no-repeat 50% 0% / cover"
                      })
                }), React.createElement(ReactNative.View, {
                  style: {
                    alignItems: "center",
                    height: 400 + 40,
                    justifyContent: "flex-end",
                    left: 0,
                    position: "absolute",
                    right: 0,
                    top: 0
                  },
                  children: React.createElement("img", {
                        alt: "",
                        height: "180",
                        src: "/_/landscape-montains.svg"
                      })
                }), React.createElement(ReactNative.View, {
                  style: {
                    alignItems: "center",
                    height: 400 + 80,
                    justifyContent: "flex-end",
                    left: Style$ReactNative.pct(75),
                    position: "absolute",
                    right: 0,
                    top: 0
                  },
                  children: React.createElement("img", {
                        alt: "",
                        height: "160",
                        src: "/_/landscape-tree.svg"
                      })
                }), React.createElement(ReactNative.View, {
                  style: {
                    left: Style$ReactNative.pct(10),
                    position: "absolute",
                    right: Style$ReactNative.pct(50),
                    top: 0
                  },
                  children: null
                }, React.createElement(ReactNative.View, {
                      style: {
                        left: -30,
                        position: "absolute",
                        top: 20
                      },
                      children: React.createElement(ReactNative.Text, {
                            accessible: false,
                            children: "a",
                            style: Object.assign({}, {
                                  fontFamily: "StoneHarbourWash",
                                  fontSize: 150,
                                  lineHeight: 150
                                }, {
                                  filter: "drop-shadow(0 2px 4px rgba(122,22,102,0.50))",
                                  WebkitTextStroke: "1px #A56C99",
                                  backgroundClip: "text",
                                  WebkitTextFillColor: "transparent",
                                  backgroundColor: "#008CDE",
                                  backgroundImage: "linear-gradient(-60deg, #008CDE 0%, #23C3AF 100%)"
                                })
                          })
                    }), React.createElement(ReactNative.View, {
                      style: {
                        left: 0,
                        position: "absolute",
                        top: 0
                      },
                      children: React.createElement(SVGFlashyTriangle3.make, {
                            width: 150,
                            height: 150
                          })
                    }), React.createElement(ReactNative.View, {
                      style: {
                        borderRadius: 100,
                        left: 28,
                        position: "absolute",
                        top: -20
                      },
                      children: React.createElement(Avatar.make, {
                            size: 88
                          })
                    })), React.createElement(ReactNative.View, {
                  style: [
                    Predefined$ReactMultiversal.styles.center,
                    {
                      backgroundColor: "#01093C"
                    }
                  ],
                  children: null
                }, React.createElement(SpacedView$ReactMultiversal.make, {
                      horizontal: /* None */7,
                      style: [
                        Predefined$ReactMultiversal.styles.rowWrap,
                        Predefined$ReactMultiversal.styles.flex
                      ],
                      children: null
                    }, React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* L */2,
                          horizontal: /* L */2,
                          children: null
                        }, React.createElement(SpacedView$ReactMultiversal.make, {
                              vertical: /* None */7,
                              horizontal: /* None */7,
                              children: React.createElement(ReactNative.Text, {
                                    children: null,
                                    style: [
                                      Font.ios.headline,
                                      Font.weight[100],
                                      theme.styles.textOnMain
                                    ]
                                  }, React.createElement(Spacer$ReactMultiversal.make, {
                                        size: /* M */3
                                      }), React.createElement(Spacer$ReactMultiversal.make, {
                                        size: /* XS */5
                                      }), "Navigation")
                            }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.View, {
                              children: Belt_Array.map(Consts.menuLinksAndMore, (function (item) {
                                      return React.createElement(ViewLink.make, {
                                                  href: item.link,
                                                  style: [
                                                    Predefined$ReactMultiversal.styles.row,
                                                    Predefined$ReactMultiversal.styles.alignCenter
                                                  ],
                                                  children: null,
                                                  key: item.link
                                                }, React.createElement(ReactNative.Text, {
                                                      children: Curry._4(item.icon, Spacer$ReactMultiversal.size(/* M */3), Spacer$ReactMultiversal.size(/* M */3), theme.colors.textOnMain, undefined),
                                                      style: {
                                                        opacity: 0.15
                                                      }
                                                    }), React.createElement(SpacedView$ReactMultiversal.make, {
                                                      vertical: /* XS */5,
                                                      horizontal: /* XS */5,
                                                      children: React.createElement(ReactNative.Text, {
                                                            children: item.text,
                                                            style: [
                                                              Font.iosEm.body,
                                                              theme.styles.textOnMain
                                                            ]
                                                          })
                                                    }));
                                    }))
                            })), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* L */2,
                          horizontal: /* L */2,
                          children: null
                        }, React.createElement(SpacedView$ReactMultiversal.make, {
                              vertical: /* None */7,
                              horizontal: /* None */7,
                              children: React.createElement(ReactNative.Text, {
                                    children: null,
                                    style: [
                                      Font.ios.headline,
                                      Font.weight[100],
                                      theme.styles.textOnMain
                                    ]
                                  }, React.createElement(Spacer$ReactMultiversal.make, {
                                        size: /* M */3
                                      }), React.createElement(Spacer$ReactMultiversal.make, {
                                        size: /* XS */5
                                      }), "Follow Me")
                            }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.View, {
                              children: null
                            }, Belt_Array.map(Consts.socialLinks, (function (item) {
                                    return React.createElement(ViewLink.make, {
                                                accessibilityLabel: item.alt,
                                                href: item.link,
                                                style: [
                                                  Predefined$ReactMultiversal.styles.row,
                                                  Predefined$ReactMultiversal.styles.alignCenter
                                                ],
                                                children: null,
                                                key: item.link
                                              }, Curry._2(item.componentFunc, theme.colors.textOnMain, Spacer$ReactMultiversal.size(/* M */3)), React.createElement(SpacedView$ReactMultiversal.make, {
                                                    vertical: /* XS */5,
                                                    horizontal: /* XS */5,
                                                    children: React.createElement(ReactNative.Text, {
                                                          children: item.text,
                                                          style: [
                                                            Font.iosEm.body,
                                                            theme.styles.textOnMain
                                                          ]
                                                        })
                                                  }));
                                  })), Belt_Array.map(Consts.socialLinks2, (function (item) {
                                    return React.createElement(ViewLink.make, {
                                                accessibilityLabel: item.alt,
                                                href: item.link,
                                                style: [
                                                  Predefined$ReactMultiversal.styles.row,
                                                  Predefined$ReactMultiversal.styles.alignCenter
                                                ],
                                                children: null,
                                                key: item.link
                                              }, React.createElement(Spacer$ReactMultiversal.make, {
                                                    size: /* XXS */6
                                                  }), Curry._2(item.componentFunc, theme.colors.textOnMain, Spacer$ReactMultiversal.size(/* S */4)), React.createElement(Spacer$ReactMultiversal.make, {
                                                    size: /* XXS */6
                                                  }), React.createElement(SpacedView$ReactMultiversal.make, {
                                                    vertical: /* XS */5,
                                                    horizontal: /* XXS */6,
                                                    children: React.createElement(ReactNative.Text, {
                                                          children: item.text,
                                                          style: [
                                                            Font.ios.body,
                                                            theme.styles.textOnMain,
                                                            Font.weight[100]
                                                          ]
                                                        })
                                                  }));
                                  })))), React.createElement(SpacedView$ReactMultiversal.make, {
                          vertical: /* L */2,
                          horizontal: /* L */2,
                          children: null
                        }, React.createElement(SpacedView$ReactMultiversal.make, {
                              vertical: /* None */7,
                              horizontal: /* None */7,
                              children: React.createElement(ReactNative.Text, {
                                    children: null,
                                    style: [
                                      Font.ios.headline,
                                      Font.weight[100],
                                      theme.styles.textOnMain
                                    ]
                                  }, React.createElement(Spacer$ReactMultiversal.make, {
                                        size: /* M */3
                                      }), React.createElement(Spacer$ReactMultiversal.make, {
                                        size: /* XS */5
                                      }), "More")
                            }), React.createElement(Spacer$ReactMultiversal.make, {}), React.createElement(ReactNative.View, {
                              children: null
                            }, Belt_Array.map(Consts.moreLinks, (function (item) {
                                    return React.createElement(ViewLink.make, {
                                                accessibilityLabel: item.alt,
                                                href: item.link,
                                                style: [
                                                  Predefined$ReactMultiversal.styles.row,
                                                  Predefined$ReactMultiversal.styles.alignCenter
                                                ],
                                                children: null,
                                                key: item.link
                                              }, Curry._2(item.componentFunc, theme.colors.textOnMain, Spacer$ReactMultiversal.size(/* M */3)), React.createElement(SpacedView$ReactMultiversal.make, {
                                                    vertical: /* XS */5,
                                                    horizontal: /* XS */5,
                                                    children: React.createElement(ReactNative.Text, {
                                                          children: item.text,
                                                          style: [
                                                            Font.iosEm.body,
                                                            theme.styles.textOnMain
                                                          ]
                                                        })
                                                  }));
                                  })), Belt_Array.map(Consts.moreLinks2, (function (item) {
                                    return React.createElement(ViewLink.make, {
                                                href: item.link,
                                                style: [
                                                  Predefined$ReactMultiversal.styles.row,
                                                  Predefined$ReactMultiversal.styles.alignCenter
                                                ],
                                                children: null,
                                                key: item.link
                                              }, React.createElement(Spacer$ReactMultiversal.make, {
                                                    size: /* M */3
                                                  }), React.createElement(Spacer$ReactMultiversal.make, {
                                                    size: /* XS */5
                                                  }), React.createElement(SpacedView$ReactMultiversal.make, {
                                                    vertical: /* XS */5,
                                                    horizontal: /* None */7,
                                                    children: React.createElement(ReactNative.Text, {
                                                          children: item.text,
                                                          style: [
                                                            Font.ios.body,
                                                            theme.styles.textOnMain,
                                                            Font.weight[100]
                                                          ]
                                                        })
                                                  }));
                                  }))))), React.createElement(ReactNative.View, {
                      style: [
                        Predefined$ReactMultiversal.styles.center,
                        {
                          maxWidth: Style$ReactNative.pct(100),
                          overflow: "hidden"
                        }
                      ],
                      children: React.createElement(ReactNative.Text, {
                            accessible: false,
                            children: "h",
                            style: Object.assign({}, {
                                  fontFamily: "StoneHarbourWash",
                                  fontSize: 200,
                                  lineHeight: 200
                                }, {
                                  fontSize: "min(200px, 50vw)",
                                  filter: "drop-shadow(0 2px 4px rgba(122,22,102,0.50))",
                                  WebkitTextStroke: "1px #A56C99",
                                  backgroundClip: "text",
                                  WebkitTextFillColor: "transparent",
                                  backgroundColor: "#008CDE",
                                  backgroundImage: "linear-gradient(to right, #FFEA53 0%, #CA3F87 50%, #1C2D98 100%)"
                                })
                          })
                    }), React.createElement(SpacedView$ReactMultiversal.make, {
                      vertical: /* L */2,
                      horizontal: /* L */2,
                      style: [
                        Predefined$ReactMultiversal.styles.rowWrap,
                        Predefined$ReactMultiversal.styles.center,
                        {
                          filter: "drop-shadow(-1px 0 0 cyan) drop-shadow(2px 0 0 red) saturate(0.75)"
                        }
                      ],
                      children: null
                    }, React.createElement(ReactNative.View, {
                          style: [
                            Predefined$ReactMultiversal.styles.rowWrap,
                            Predefined$ReactMultiversal.styles.flexShrink
                          ],
                          children: null
                        }, React.createElement(ReactNative.Text, {
                              children: "Made with ",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(TextLink.make, {
                              children: "ReScript, ",
                              href: "https://rescript-lang.org/",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(TextLink.make, {
                              children: "React Native",
                              href: "https://reactnative.dev",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(TextLink.make, {
                              children: " Web, ",
                              href: "https://necolas.github.io/react-native-web/",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(TextLink.make, {
                              children: "Next.js",
                              href: "https://nextjs.org",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(ReactNative.Text, {
                              children: " and ",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(TextLink.make, {
                              children: "ReScript React Native",
                              href: "https://rescript-react-native.github.io",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            }), React.createElement(ReactNative.Text, {
                              children: ". ",
                              style: [
                                Font.ios.footnote,
                                theme.styles.textOnMain
                              ]
                            })), React.createElement(TextLink.make, {
                          children: "100% Over-engineered source available on GitHub",
                          href: "https://github.com/MoOx/moox",
                          style: [
                            Font.ios.footnote,
                            theme.styles.textOnMain
                          ]
                        }))));
}

var make = WebsiteFooter;

export {
  make ,
  
}
/* T Not a pure module */
