// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function WindowSizeFilter$SMax(Props) {
  var style = Props.style;
  var children = Props.children;
  var tmp = {
    className: "WindowSizeFilterSMax"
  };
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  return React.createElement("div", tmp, Belt_Option.getWithDefault(children, null));
}

var SMax = {
  make: WindowSizeFilter$SMax
};

function WindowSizeFilter$MMin(Props) {
  var style = Props.style;
  var children = Props.children;
  var tmp = {
    className: "WindowSizeFilterMMin"
  };
  if (style !== undefined) {
    tmp.style = Caml_option.valFromOption(style);
  }
  return React.createElement("div", tmp, Belt_Option.getWithDefault(children, null));
}

var MMin = {
  make: WindowSizeFilter$MMin
};

export {
  SMax ,
  MMin ,
  
}
/* react Not a pure module */
