// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Process from "process";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function contentTypeString(contentType) {
  if (contentType === "resume") {
    return "resume";
  } else if (contentType === "talks") {
    return "talks";
  } else {
    return "blog";
  }
}

function getOne(filename, contentType) {
  var fullPath = Path.join(Path.join(Path.join(Process.cwd(), "content"), contentTypeString(contentType)), filename);
  if (!Fs.existsSync(fullPath)) {
    return ;
  }
  var fileContents = Fs.readFileSync(fullPath, "utf8");
  return {
          slug: filename.replace(/\.json$/, ""),
          json: JSON.parse(fileContents)
        };
}

function getAll(contentType) {
  var filenames = Fs.readdirSync(Path.join(Path.join(Process.cwd(), "content"), contentTypeString(contentType)));
  return Belt_Array.reduce(Belt_Array.keep(filenames, (function (file) {
                    return file.endsWith(".json");
                  })), [], (function (acc, filename) {
                var content = getOne(filename, contentType);
                if (content !== undefined) {
                  acc.push(content);
                }
                return acc;
              }));
}

export {
  contentTypeString ,
  getOne ,
  getAll ,
  
}
/* fs Not a pure module */
