// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Js_null from "rescript/lib/es6/js_null.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function decode(id, rawJson) {
  var data;
  try {
    data = {
      body: Js_null.fromOption(Belt_Option.map(Belt_Option.flatMap(Belt_Option.flatMap(Js_json.decodeObject(rawJson), (function (json) {
                          return Js_dict.get(json, "body");
                        })), Js_json.decodeObject), (function (body) {
                  return body;
                }))),
      conference: Js_null.fromOption(Json_decode.optional((function (param) {
                  return Json_decode.field("conference", Json_decode.string, param);
                }), rawJson)),
      date: Json_decode.field("date", Json_decode.string, rawJson),
      lang: Js_null.fromOption(Json_decode.optional((function (param) {
                  return Json_decode.field("lang", Json_decode.string, param);
                }), rawJson)),
      slides: Js_null.fromOption(Json_decode.optional((function (param) {
                  return Json_decode.field("slides", Json_decode.string, param);
                }), rawJson)),
      slidesEmbed: Js_null.fromOption(Json_decode.optional((function (param) {
                  return Json_decode.field("slidesEmbed", Json_decode.string, param);
                }), rawJson)),
      id: id,
      title: Json_decode.field("title", Json_decode.string, rawJson),
      video: Js_null.fromOption(Json_decode.optional((function (param) {
                  return Json_decode.field("video", Json_decode.string, param);
                }), rawJson)),
      videoEmbed: Js_null.fromOption(Json_decode.optional((function (param) {
                  return Json_decode.field("videoEmbed", Json_decode.string, param);
                }), rawJson))
    };
  }
  catch (raw_str){
    var str = Caml_js_exceptions.internalToOCamlException(raw_str);
    if (str.RE_EXN_ID === Json_decode.DecodeError) {
      return {
              TAG: /* Error */1,
              _0: str._1
            };
    }
    throw str;
  }
  return {
          TAG: /* Ok */0,
          _0: data
        };
}

function orderByDate(posts) {
  return posts.slice().sort(function (a, b) {
              var aV = a.date;
              var bV = b.date;
              if (aV === bV) {
                return 0;
              } else if (aV > bV) {
                return -1;
              } else {
                return 1;
              }
            });
}

export {
  decode ,
  orderByDate ,
  
}
/* No side effect */
